const languages=['ko','en','ja','zh-Hans','zh-Hant'];
const reviewLinks={ko:'https://m.site.naver.com/242PR',en:'https://m.site.naver.com/2430v',ja:'https://m.site.naver.com/2430v','zh-Hans':'https://m.site.naver.com/2430v','zh-Hant':'https://m.site.naver.com/2430v'};
const copy={
  ko:{pageTitle:'포토리뷰 이벤트 | BlueBlack Pen Shop',back:'디지털 가이드로 돌아가기',eyebrow:'BLUEBLACK STORE EVENT',title:'포토리뷰를 남기고 잉크를 받아보세요',intro:'매장에서 구매한 제품 사진과 함께 리뷰를 남긴 뒤 완료 화면을 직원에게 보여주세요. 랜덤 5ml 소분 잉크 1병을 증정합니다.',rewardLabel:'PHOTO REVIEW GIFT',rewardLead:'포토리뷰 완료 시',rewardMain:'랜덤 5ml 소분 잉크 1병',primary:'네이버 지도 포토리뷰 열기',ruleTitle:'참여 전 꼭 확인해 주세요',rules:['제품 사진 첨부가 필수인 포토리뷰 이벤트입니다.','이벤트 참여 및 증정은 1일 1인 1회만 가능합니다.','사진에 매장 손님이나 직원의 얼굴이 나오지 않도록 촬영해 주세요.'],sectionEyebrow:'HOW TO PARTICIPATE',guideTitle:'참여 방법',guideBody:'휴대폰에서는 QR을 다시 촬영할 필요 없이 아래 리뷰 페이지 열기 버튼을 이용하면 됩니다.',steps:['결제 후 직원에게 영수증 발급을 요청해 주세요.','네이버 지도 리뷰 페이지로 이동해 주세요.','구매 인증 후 제품 사진을 반드시 첨부해 주세요. 다른 손님이나 직원의 얼굴은 촬영하지 말아 주세요.','포토리뷰를 남긴 뒤 완료 화면을 직원에게 보여주세요.'],qrTitle:'네이버 지도 포토리뷰',qrBody:'다른 기기로 보고 있다면 QR을 스캔해 주세요.',secondary:'포토리뷰 페이지 열기',posterEyebrow:'KOREAN GUIDE',posterTitle:'한글 이벤트 안내',posterBody:'매장에 비치된 안내문과 같은 내용을 웹에서도 크게 확인할 수 있습니다.',posterHeader:'참여 방법',posterLabel:'영수증 포토리뷰 이벤트',posterGift:'5ml 소분 잉크 1병 랜덤 증정',notice:'제품 사진 첨부가 필수이며, 이벤트는 1일 1인 1회 참여할 수 있습니다. 촬영 시 매장 손님과 직원의 얼굴이 나오지 않도록 부탁드립니다.',footer:'BlueBlack Pen Shop 매장 이벤트 안내'},
  en:{pageTitle:'Photo Review Event | BlueBlack Pen Shop',back:'Back to the digital guide',eyebrow:'BLUEBLACK STORE EVENT',title:'Leave a photo review and receive an ink sample',intro:'Post a review with a photo of your purchase, then show the completed review to our staff. You will receive one random 5ml ink sample.',rewardLabel:'PHOTO REVIEW GIFT',rewardLead:'After completing a photo review',rewardMain:'One random 5ml ink sample',primary:'Open Google Maps photo reviews',ruleTitle:'Please check before participating',rules:['A product photo is required for this photo review event.','Participation and gifts are limited to once per person per day.','Please make sure no customers or staff members appear in your photo.'],sectionEyebrow:'HOW TO PARTICIPATE',guideTitle:'How to participate',guideBody:'On your phone, use the review-page button below instead of trying to scan the QR code on the same screen.',steps:['Ask our staff for a receipt after payment.','Open the BlueBlack review page on Google Maps.','Verify your purchase and attach a product photo. Do not include customers or staff in the photo.','Complete your photo review and show it to our staff.'],qrTitle:'Google Maps photo reviews',qrBody:'Scan this QR code when viewing the guide on another device.',secondary:'Open photo review page',posterEyebrow:'ENGLISH GUIDE',posterTitle:'English event guide',posterBody:'The same information displayed in the store is available here in a mobile-friendly format.',posterHeader:'How to Participate',posterLabel:'Photo Review Event',posterGift:'Get one random 5ml ink sample',notice:'A product photo is required. Participation is limited to once per person per day. Please do not include customers or staff members in your photo.',footer:'BlueBlack Pen Shop Store Event'},
  ja:{pageTitle:'フォトレビューイベント | BlueBlack Pen Shop',back:'デジタルガイドに戻る',eyebrow:'BLUEBLACK STORE EVENT',title:'フォトレビュー投稿でインクサンプルをプレゼント',intro:'ご購入商品の写真付きレビューを投稿し、完了画面をスタッフにお見せください。ランダムで5mlインクサンプルを1本プレゼントします。',rewardLabel:'PHOTO REVIEW GIFT',rewardLead:'フォトレビュー完了で',rewardMain:'ランダム5mlインクサンプル 1本',primary:'Googleマップのフォトレビューを開く',ruleTitle:'参加前に必ずご確認ください',rules:['商品写真の添付が必須のフォトレビューイベントです。','参加およびプレゼントは1日1名様1回までです。','写真に他のお客様やスタッフの顔が写らないようにしてください。'],sectionEyebrow:'HOW TO PARTICIPATE',guideTitle:'参加方法',guideBody:'スマートフォンでは、同じ画面のQRを読み取る代わりに下のボタンをご利用ください。',steps:['お会計後、スタッフにレシートの発行をお申し付けください。','GoogleマップのBlueBlackレビューページを開いてください。','購入を証明し、商品写真を必ず添付してください。他のお客様やスタッフの顔は撮影しないでください。','フォトレビューを投稿し、完了画面をスタッフにお見せください。'],qrTitle:'Googleマップ フォトレビュー',qrBody:'別の端末で表示している場合はQRを読み取ってください。',secondary:'フォトレビューページを開く',posterEyebrow:'JAPANESE GUIDE',posterTitle:'レビューイベント案内',posterBody:'店頭案内と同じ内容をスマートフォンでも見やすく確認できます。',posterHeader:'参加方法',posterLabel:'フォトレビューイベント',posterGift:'ランダム5mlインクサンプル 1本',notice:'商品写真の添付が必須です。参加は1日1名様1回までです。撮影時は他のお客様やスタッフの顔が写らないようにしてください。',footer:'BlueBlack Pen Shop 店頭イベント'},
  'zh-Hans':{pageTitle:'图片评价活动 | BlueBlack Pen Shop',back:'返回数字指南',eyebrow:'BLUEBLACK STORE EVENT',title:'留下图片评价，领取墨水分装礼品',intro:'请附上所购商品的照片并完成评价，然后向店员出示完成页面。可获赠随机5ml墨水分装1瓶。',rewardLabel:'PHOTO REVIEW GIFT',rewardLead:'完成图片评价即可获得',rewardMain:'随机5ml墨水分装 1瓶',primary:'打开 Google 地图图片评价',ruleTitle:'参与前请务必确认',rules:['本活动必须在评价中附上商品照片。','每人每天仅限参与并领取一次赠品。','拍照时请勿拍到其他顾客或店员的脸。'],sectionEyebrow:'HOW TO PARTICIPATE',guideTitle:'参与方法',guideBody:'使用手机时，无需扫描同一屏幕上的二维码，直接点击下方按钮即可。',steps:['付款后请向店员索取小票。','打开 Google 地图上的 BlueBlack 评价页面。','验证购买记录后必须附上商品照片，请勿拍到其他顾客或店员的脸。','完成图片评价后，将完成页面出示给店员。'],qrTitle:'Google 地图图片评价',qrBody:'使用其他设备查看时，可扫描此二维码。',secondary:'打开图片评价页面',posterEyebrow:'CHINESE GUIDE',posterTitle:'评价活动指南',posterBody:'店内展示的活动内容也可在手机上清晰查看。',posterHeader:'参与方法',posterLabel:'图片评价活动',posterGift:'随机赠送5ml墨水分装1瓶',notice:'必须附上商品照片。每人每天仅限参与一次。拍照时请勿拍到其他顾客或店员的脸。',footer:'BlueBlack Pen Shop 门店活动'},
  'zh-Hant':{pageTitle:'照片評論活動 | BlueBlack Pen Shop',back:'返回數位指南',eyebrow:'BLUEBLACK STORE EVENT',title:'留下照片評論，領取墨水分裝贈品',intro:'請附上所購商品的照片並完成評論，再向店員出示完成頁面。可獲贈隨機5ml墨水分裝1瓶。',rewardLabel:'PHOTO REVIEW GIFT',rewardLead:'完成照片評論即可獲得',rewardMain:'隨機5ml墨水分裝 1瓶',primary:'開啟 Google 地圖照片評論',ruleTitle:'參與前請務必確認',rules:['本活動必須在評論中附上商品照片。','每人每天僅限參與並領取一次贈品。','拍照時請勿拍到其他顧客或店員的臉。'],sectionEyebrow:'HOW TO PARTICIPATE',guideTitle:'參與方式',guideBody:'使用手機時，不必掃描同一畫面上的QR碼，直接點擊下方按鈕即可。',steps:['付款後請向店員索取收據。','開啟 Google 地圖上的 BlueBlack 評論頁面。','驗證購買紀錄後必須附上商品照片，請勿拍到其他顧客或店員的臉。','完成照片評論後，將完成頁面出示給店員。'],qrTitle:'Google 地圖照片評論',qrBody:'使用其他裝置查看時，可掃描此QR碼。',secondary:'開啟照片評論頁面',posterEyebrow:'CHINESE GUIDE',posterTitle:'評論活動指南',posterBody:'店內展示的活動內容也可在手機上清楚查看。',posterHeader:'參與方式',posterLabel:'照片評論活動',posterGift:'隨機贈送5ml墨水分裝1瓶',notice:'必須附上商品照片。每人每天僅限參與一次。拍照時請勿拍到其他顧客或店員的臉。',footer:'BlueBlack Pen Shop 門市活動'}
};
function normalizeLanguage(value){
  const language=(value||'ko').toLowerCase();
  if(language.includes('hant')||language.startsWith('zh-tw')||language.startsWith('zh-hk'))return'zh-Hant';
  if(language.startsWith('zh'))return'zh-Hans';
  if(language.startsWith('ja'))return'ja';
  if(language.startsWith('en'))return'en';
  return'ko';
}
function getLanguage(){return normalizeLanguage(new URLSearchParams(location.search).get('lang')||localStorage.getItem('blueblack-language')||navigator.language);}
function applyLanguage(language,{replaceUrl=false}={}){
  const lang=languages.includes(language)?language:'ko';
  const text=copy[lang]||copy.ko;
  document.documentElement.lang=lang;
  document.title=text.pageTitle;
  localStorage.setItem('blueblack-language',lang);
  document.querySelectorAll('[data-copy]').forEach(node=>{const key=node.dataset.copy;if(text[key])node.textContent=text[key];});
  document.querySelectorAll('[data-step]').forEach(node=>{const index=Number(node.dataset.step);node.textContent=text.steps[index]||'';});
  document.querySelectorAll('[data-rule]').forEach(node=>{const index=Number(node.dataset.rule);node.textContent=text.rules[index]||'';});
  document.querySelectorAll('[data-review-link]').forEach(node=>{node.href=reviewLinks[lang];});
  document.querySelectorAll('[data-review-qr]').forEach(qr=>{qr.src=lang==='ko'?'./review-qr-ko.svg':'./review-qr-en.svg';qr.alt=text.qrTitle;});
  const back=document.querySelector('[data-review-back]');
  if(back)back.href=`../?lang=${encodeURIComponent(lang)}`;
  document.querySelectorAll('[data-review-lang]').forEach(button=>button.setAttribute('aria-pressed',String(button.dataset.reviewLang===lang)));
  if(replaceUrl){const url=new URL(location.href);url.searchParams.set('lang',lang);history.replaceState(null,'',url);}
}
document.querySelectorAll('[data-review-lang]').forEach(button=>button.addEventListener('click',()=>applyLanguage(button.dataset.reviewLang,{replaceUrl:true})));
applyLanguage(getLanguage());