const languages=['ko','en','ja','zh-Hans','zh-Hant'];
const reviewLinks={ko:'https://m.site.naver.com/242PR',en:'https://m.site.naver.com/2430v',ja:'https://m.site.naver.com/2430v','zh-Hans':'https://m.site.naver.com/2430v','zh-Hant':'https://m.site.naver.com/2430v'};
const copy={
  ko:{pageTitle:'영수증 리뷰 이벤트 | BlueBlack Pen Shop',back:'디지털 가이드로 돌아가기',eyebrow:'BLUEBLACK STORE EVENT',title:'영수증 리뷰를 남기고 잉크를 받아보세요',intro:'매장에서 구매한 제품의 리뷰를 남긴 뒤 완료 화면을 직원에게 보여주세요. 랜덤 5ml 소분 잉크 1병을 증정합니다.',rewardLabel:'REVIEW GIFT',rewardLead:'리뷰 완료 시',rewardMain:'랜덤 5ml 소분 잉크 1병',primary:'네이버 지도 리뷰 열기',sectionEyebrow:'HOW TO PARTICIPATE',guideTitle:'참여 방법',guideBody:'휴대폰에서는 QR을 다시 촬영할 필요 없이 아래 리뷰 페이지 열기 버튼을 이용하면 됩니다.',steps:['결제 후 직원에게 영수증 발급을 요청해 주세요.','네이버 지도 리뷰 페이지로 이동해 주세요.','영수증으로 구매를 인증하고 제품 사진을 촬영해 주세요.','정성스러운 리뷰를 남긴 뒤 완료 화면을 직원에게 보여주세요.'],qrTitle:'네이버 지도 리뷰',qrBody:'다른 기기로 보고 있다면 QR을 스캔해 주세요.',secondary:'리뷰 페이지 열기',posterEyebrow:'KOREAN GUIDE',posterTitle:'한글 이벤트 안내',posterBody:'매장에 비치된 안내문과 같은 내용을 웹에서도 크게 확인할 수 있습니다.',posterHeader:'참여 방법',posterLabel:'영수증 리뷰 이벤트',posterGift:'5ml 소분 잉크 1병 랜덤 증정',notice:'리뷰 작성을 완료한 뒤 해당 화면을 매장 직원에게 보여주세요. 증정 잉크의 색상은 랜덤으로 제공됩니다.',footer:'BlueBlack Pen Shop 매장 이벤트 안내'},
  en:{pageTitle:'Receipt Review Event | BlueBlack Pen Shop',back:'Back to the digital guide',eyebrow:'BLUEBLACK STORE EVENT',title:'Leave a review and receive an ink sample',intro:'After reviewing your purchase, show the completed review to our staff. You will receive one random 5ml ink sample.',rewardLabel:'REVIEW GIFT',rewardLead:'After completing your review',rewardMain:'One random 5ml ink sample',primary:'Open Google Maps reviews',sectionEyebrow:'HOW TO PARTICIPATE',guideTitle:'How to participate',guideBody:'On your phone, use the review-page button below instead of trying to scan the QR code on the same screen.',steps:['Ask our staff for a receipt after payment.','Open the BlueBlack review page on Google Maps.','Verify your purchase and take a photo of the product.','Write a thoughtful review and show the completed review to our staff.'],qrTitle:'Google Maps reviews',qrBody:'Scan this QR code when viewing the guide on another device.',secondary:'Open review page',posterEyebrow:'ENGLISH GUIDE',posterTitle:'English event guide',posterBody:'The same information displayed in the store is available here in a mobile-friendly format.',posterHeader:'How to Participate',posterLabel:'Review Event',posterGift:'Get one random 5ml ink sample',notice:'Please show the completed review screen to our staff. The ink color is provided at random.',footer:'BlueBlack Pen Shop Store Event'},
  ja:{pageTitle:'レシートレビューイベント | BlueBlack Pen Shop',back:'デジタルガイドに戻る',eyebrow:'BLUEBLACK STORE EVENT',title:'レビュー投稿でインクサンプルをプレゼント',intro:'ご購入商品のレビュー投稿後、完了画面をスタッフにお見せください。ランダムで5mlインクサンプルを1本プレゼントします。',rewardLabel:'REVIEW GIFT',rewardLead:'レビュー完了で',rewardMain:'ランダム5mlインクサンプル 1本',primary:'Googleマップのレビューを開く',sectionEyebrow:'HOW TO PARTICIPATE',guideTitle:'参加方法',guideBody:'スマートフォンでは、同じ画面のQRを読み取る代わりに下のボタンをご利用ください。',steps:['お会計後、スタッフにレシートの発行をお申し付けください。','GoogleマップのBlueBlackレビューページを開いてください。','購入を証明し、商品の写真を撮影してください。','レビューを投稿し、完了画面をスタッフにお見せください。'],qrTitle:'Googleマップ レビュー',qrBody:'別の端末で表示している場合はQRを読み取ってください。',secondary:'レビューページを開く',posterEyebrow:'JAPANESE GUIDE',posterTitle:'レビューイベント案内',posterBody:'店頭案内と同じ内容をスマートフォンでも見やすく確認できます。',posterHeader:'参加方法',posterLabel:'レビューイベント',posterGift:'ランダム5mlインクサンプル 1本',notice:'レビュー完了画面をスタッフにお見せください。インクの色はランダムです。',footer:'BlueBlack Pen Shop 店頭イベント'},
  'zh-Hans':{pageTitle:'小票评价活动 | BlueBlack Pen Shop',back:'返回数字指南',eyebrow:'BLUEBLACK STORE EVENT',title:'留下评价，领取墨水分装礼品',intro:'完成购买商品的评价后，请向店员出示评价完成页面。可获赠随机5ml墨水分装1瓶。',rewardLabel:'REVIEW GIFT',rewardLead:'完成评价即可获得',rewardMain:'随机5ml墨水分装 1瓶',primary:'打开 Google 地图评价',sectionEyebrow:'HOW TO PARTICIPATE',guideTitle:'参与方法',guideBody:'使用手机时，无需扫描同一屏幕上的二维码，直接点击下方按钮即可。',steps:['付款后请向店员索取小票。','打开 Google 地图上的 BlueBlack 评价页面。','验证购买记录并拍摄商品照片。','认真留下评价后，将完成页面出示给店员。'],qrTitle:'Google 地图评价',qrBody:'使用其他设备查看时，可扫描此二维码。',secondary:'打开评价页面',posterEyebrow:'CHINESE GUIDE',posterTitle:'评价活动指南',posterBody:'店内展示的活动内容也可在手机上清晰查看。',posterHeader:'参与方法',posterLabel:'评价活动',posterGift:'随机赠送5ml墨水分装1瓶',notice:'请将评价完成页面出示给店员。赠送的墨水颜色为随机提供。',footer:'BlueBlack Pen Shop 门店活动'},
  'zh-Hant':{pageTitle:'收據評論活動 | BlueBlack Pen Shop',back:'返回數位指南',eyebrow:'BLUEBLACK STORE EVENT',title:'留下評論，領取墨水分裝贈品',intro:'完成購買商品的評論後，請向店員出示評論完成頁面。可獲贈隨機5ml墨水分裝1瓶。',rewardLabel:'REVIEW GIFT',rewardLead:'完成評論即可獲得',rewardMain:'隨機5ml墨水分裝 1瓶',primary:'開啟 Google 地圖評論',sectionEyebrow:'HOW TO PARTICIPATE',guideTitle:'參與方式',guideBody:'使用手機時，不必掃描同一畫面上的QR碼，直接點擊下方按鈕即可。',steps:['付款後請向店員索取收據。','開啟 Google 地圖上的 BlueBlack 評論頁面。','驗證購買紀錄並拍攝商品照片。','認真留下評論後，將完成頁面出示給店員。'],qrTitle:'Google 地圖評論',qrBody:'使用其他裝置查看時，可掃描此QR碼。',secondary:'開啟評論頁面',posterEyebrow:'CHINESE GUIDE',posterTitle:'評論活動指南',posterBody:'店內展示的活動內容也可在手機上清楚查看。',posterHeader:'參與方式',posterLabel:'評論活動',posterGift:'隨機贈送5ml墨水分裝1瓶',notice:'請將評論完成頁面出示給店員。贈送的墨水顏色為隨機提供。',footer:'BlueBlack Pen Shop 門市活動'}
};
function normalizeLanguage(value){
  const language=(value||'ko').toLowerCase();
  if(language.includes('hant')||language.startsWith('zh-tw')||language.startsWith('zh-hk'))return'zh-Hant';
  if(language.startsWith('zh'))return'zh-Hans';
  if(language.startsWith('ja'))return'ja';
  if(language.startsWith('en'))return'en';
  return'ko';
}
function getLanguage(){return normalizeLanguage(new URLSearchParams(location.search).get('lang')||localStorage.getItem('blueblack-language')||navigator.language);}
function applyLanguage(language,{replaceUrl=false}={}){
  const lang=languages.includes(language)?language:'ko';
  const text=copy[lang]||copy.ko;
  document.documentElement.lang=lang;
  document.title=text.pageTitle;
  localStorage.setItem('blueblack-language',lang);
  document.querySelectorAll('[data-copy]').forEach(node=>{const key=node.dataset.copy;if(text[key])node.textContent=text[key];});
  document.querySelectorAll('[data-step]').forEach(node=>{const index=Number(node.dataset.step);node.textContent=text.steps[index]||'';});
  document.querySelectorAll('[data-review-link]').forEach(node=>{node.href=reviewLinks[lang];});
  document.querySelectorAll('[data-review-qr]').forEach(qr=>{qr.src=lang==='ko'?'./review-qr-ko.svg':'./review-qr-en.svg';qr.alt=text.qrTitle;});
  const back=document.querySelector('[data-review-back]');
  if(back)back.href=`../?lang=${encodeURIComponent(lang)}`;
  document.querySelectorAll('[data-review-lang]').forEach(button=>button.setAttribute('aria-pressed',String(button.dataset.reviewLang===lang)));
  if(replaceUrl){const url=new URL(location.href);url.searchParams.set('lang',lang);history.replaceState(null,'',url);}
}
document.querySelectorAll('[data-review-lang]').forEach(button=>button.addEventListener('click',()=>applyLanguage(button.dataset.reviewLang,{replaceUrl:true})));
applyLanguage(getLanguage());