const languages=['ko','en','ja','zh-Hans','zh-Hant'];
const copy={
  ko:{pageTitle:'블루블랙 최신 소식 | BlueBlack Pen Shop',back:'디지털 가이드로 돌아가기',title:'블루블랙의 새로운 소식을 만나보세요',intro:'신제품, 재입고, 기존 제품 소개와 매장 소식을 인스타그램에서 자동으로 불러옵니다.',scheduleTitle:'매주 화요일·목요일',scheduleBody:'정기 제품 소개와 새로운 입고 소식을 확인해 보세요. 별도의 사이트 게시물 등록 없이 SNS에 올라온 내용을 보여드립니다.',feedTitle:'인스타그램 최신 소식',feedBody:'게시물은 인스타그램에 새 글이 올라오면 자동으로 갱신됩니다.',loadingTitle:'최신 게시물을 불러오는 중입니다',loadingBody:'네트워크 환경이나 인스타그램 설정에 따라 표시까지 잠시 걸릴 수 있습니다.',fallbackTitle:'게시물을 불러오지 못했습니다',fallbackBody:'인스타그램 앱 또는 웹에서 최신 소식을 바로 확인해 주세요.',instagram:'인스타그램 열기',channelsTitle:'다른 채널에서도 확인하세요',channelsBody:'같은 소식은 각 채널의 운영 방식에 맞게 게시됩니다.',xTitle:'X 소식',xBody:'제품 소개와 빠른 매장 소식을 확인합니다.',naverTitle:'네이버 지도 소식',naverBody:'매장 방문 전 공지와 새로운 소식을 확인합니다.',websiteTitle:'공식 홈페이지',websiteBody:'신제품과 상품 정보를 확인합니다.',note:'인스타그램의 로그인 상태, 개인정보 보호 설정 또는 플랫폼 정책에 따라 일부 게시물이 표시되지 않을 수 있습니다.',footer:'BlueBlack Pen Shop 최신 소식'},
  en:{pageTitle:'BlueBlack News | BlueBlack Pen Shop',back:'Back to the digital guide',title:'See what is new at BlueBlack',intro:'New arrivals, restocks, product highlights and store news are loaded automatically from Instagram.',scheduleTitle:'Every Tuesday and Thursday',scheduleBody:'See regular product features and new arrivals without separate updates on this website.',feedTitle:'Latest Instagram posts',feedBody:'This section updates automatically when a new Instagram post is published.',loadingTitle:'Loading the latest posts',loadingBody:'Display may take a moment depending on your network and Instagram settings.',fallbackTitle:'The posts could not be loaded',fallbackBody:'Open Instagram to see the latest BlueBlack updates.',instagram:'Open Instagram',channelsTitle:'See more channels',channelsBody:'The same news is shared in a format suited to each channel.',xTitle:'Updates on X',xBody:'See quick product and store updates.',naverTitle:'Naver Map updates',naverBody:'Check store notices before your visit.',websiteTitle:'Official website',websiteBody:'Browse new arrivals and product information.',note:'Some posts may not appear depending on Instagram login, privacy settings or platform policies.',footer:'BlueBlack Pen Shop News'},
  ja:{pageTitle:'BlueBlack 最新情報 | BlueBlack Pen Shop',back:'デジタルガイドに戻る',title:'BlueBlackの最新情報をご覧ください',intro:'新商品、再入荷、商品紹介、店舗のお知らせをInstagramから自動で表示します。',scheduleTitle:'毎週火曜日・木曜日',scheduleBody:'定期の商品紹介と新しい入荷情報をご確認ください。サイト用の記事を別途登録する必要はありません。',feedTitle:'Instagram 最新情報',feedBody:'Instagramに新しい投稿が公開されると自動で更新されます。',loadingTitle:'最新投稿を読み込んでいます',loadingBody:'通信環境やInstagramの設定により表示まで時間がかかる場合があります。',fallbackTitle:'投稿を読み込めませんでした',fallbackBody:'Instagramで最新情報をご確認ください。',instagram:'Instagramを開く',channelsTitle:'ほかのチャンネル',channelsBody:'同じ情報を各チャンネルに合わせた形式で発信しています。',xTitle:'Xのお知らせ',xBody:'商品紹介や店舗の最新情報を確認できます。',naverTitle:'NAVERマップのお知らせ',naverBody:'ご来店前に店舗のお知らせをご確認ください。',websiteTitle:'公式サイト',websiteBody:'新商品と商品情報をご確認ください。',note:'Instagramのログイン状況、公開設定、プラットフォームの仕様により一部の投稿が表示されない場合があります。',footer:'BlueBlack Pen Shop 最新情報'},
  'zh-Hans':{pageTitle:'BlueBlack 最新消息 | BlueBlack Pen Shop',back:'返回数字指南',title:'查看 BlueBlack 的最新消息',intro:'自动显示 Instagram 上的新产品、补货、产品介绍和门店消息。',scheduleTitle:'每周二、周四',scheduleBody:'查看定期产品介绍和新品到货信息，无需在本网站重复发布。',feedTitle:'Instagram 最新消息',feedBody:'Instagram 发布新内容后，此处会自动更新。',loadingTitle:'正在加载最新内容',loadingBody:'根据网络环境和 Instagram 设置，显示可能需要一些时间。',fallbackTitle:'无法加载内容',fallbackBody:'请前往 Instagram 查看 BlueBlack 的最新消息。',instagram:'打开 Instagram',channelsTitle:'其他官方渠道',channelsBody:'相同消息会根据各平台的方式发布。',xTitle:'X 最新消息',xBody:'查看产品介绍和门店即时消息。',naverTitle:'NAVER 地图消息',naverBody:'到店前查看门店通知和最新消息。',websiteTitle:'官方网站',websiteBody:'查看新品和商品信息。',note:'根据 Instagram 登录状态、隐私设置或平台政策，部分内容可能无法显示。',footer:'BlueBlack Pen Shop 最新消息'},
  'zh-Hant':{pageTitle:'BlueBlack 最新消息 | BlueBlack Pen Shop',back:'返回數位指南',title:'查看 BlueBlack 的最新消息',intro:'自動顯示 Instagram 上的新產品、補貨、產品介紹與門市消息。',scheduleTitle:'每週二、週四',scheduleBody:'查看定期產品介紹與新品到貨資訊，不需要在本網站重複發布。',feedTitle:'Instagram 最新消息',feedBody:'Instagram 發布新內容後，此處會自動更新。',loadingTitle:'正在載入最新內容',loadingBody:'依網路環境與 Instagram 設定，顯示可能需要一些時間。',fallbackTitle:'無法載入內容',fallbackBody:'請前往 Instagram 查看 BlueBlack 的最新消息。',instagram:'開啟 Instagram',channelsTitle:'其他官方頻道',channelsBody:'相同消息會依各平台的方式發布。',xTitle:'X 最新消息',xBody:'查看產品介紹與門市即時消息。',naverTitle:'NAVER 地圖消息',naverBody:'到店前查看門市公告與最新消息。',websiteTitle:'官方網站',websiteBody:'查看新品與商品資訊。',note:'依 Instagram 登入狀態、隱私設定或平台政策，部分內容可能無法顯示。',footer:'BlueBlack Pen Shop 最新消息'}
};
function normalize(value){const lang=(value||'ko').toLowerCase();if(lang.includes('hant')||lang.startsWith('zh-tw')||lang.startsWith('zh-hk'))return'zh-Hant';if(lang.startsWith('zh'))return'zh-Hans';if(lang.startsWith('ja'))return'ja';if(lang.startsWith('en'))return'en';return'ko';}
function currentLanguage(){return normalize(new URLSearchParams(location.search).get('lang')||localStorage.getItem('blueblack-language')||navigator.language);}
function applyLanguage(language,{replaceUrl=false}={}){const lang=languages.includes(language)?language:'ko';const text=copy[lang]||copy.ko;document.documentElement.lang=lang;document.title=text.pageTitle;localStorage.setItem('blueblack-language',lang);document.querySelectorAll('[data-news-copy]').forEach(node=>{const value=text[node.dataset.newsCopy];if(value)node.textContent=value;});const back=document.querySelector('[data-news-back]');if(back)back.href=`../?lang=${encodeURIComponent(lang)}`;document.querySelectorAll('[data-news-lang]').forEach(button=>button.setAttribute('aria-pressed',String(button.dataset.newsLang===lang)));if(replaceUrl){const url=new URL(location.href);url.searchParams.set('lang',lang);history.replaceState(null,'',url);}}
function loadInstagramEmbed(){const shell=document.querySelector('[data-instagram-shell]');const loading=document.querySelector('[data-instagram-loading]');const fallback=document.querySelector('[data-instagram-fallback]');if(!shell)return;let resolved=false;const finish=()=>{if(resolved)return;const iframe=shell.querySelector('iframe');if(!iframe)return;resolved=true;if(loading)loading.hidden=true;if(fallback)fallback.classList.remove('is-visible');};const observer=new MutationObserver(finish);observer.observe(shell,{childList:true,subtree:true});const script=document.createElement('script');script.async=true;script.src='https://www.instagram.com/embed.js';script.onload=()=>{window.instgrm?.Embeds?.process();setTimeout(finish,900)};script.onerror=()=>{if(loading)loading.hidden=true;if(fallback)fallback.classList.add('is-visible')};document.body.appendChild(script);setTimeout(()=>{finish();if(!resolved){if(loading)loading.hidden=true;if(fallback)fallback.classList.add('is-visible')}},9000);}
document.querySelectorAll('[data-news-lang]').forEach(button=>button.addEventListener('click',()=>applyLanguage(button.dataset.newsLang,{replaceUrl:true})));
applyLanguage(currentLanguage());
loadInstagramEmbed();