#!/usr/bin/env python3
"""Download official BlueBlack product images and generate the browser image map."""

from __future__ import annotations

import io
import json
import re
import sys
from pathlib import Path
from typing import Iterable
from urllib.parse import urljoin

import requests
from bs4 import BeautifulSoup
from PIL import Image, ImageOps

ROOT = Path(__file__).resolve().parents[2]
GUIDE = ROOT / "guide"
DATA_FILES = [
    GUIDE / "data" / "catalog.js",
    GUIDE / "data" / "premium.js",
    GUIDE / "data" / "expanded-products.js",
]
OUTPUT_DIR = GUIDE / "assets" / "products"
OUTPUT_MAP = GUIDE / "data" / "product-images.js"
TIMEOUT = 30
USER_AGENT = (
    "Mozilla/5.0 (Windows NT 10.0; Win64; x64) "
    "AppleWebKit/537.36 (KHTML, like Gecko) "
    "Chrome/126.0 Safari/537.36 BlueBlackGuideImageSync/1.0"
)

PRODUCT_PATTERN = re.compile(
    r"\{id:'(?P<id>[^']+)'.*?name:'(?P<name>[^']+)'.*?url:'(?P<url>https?://[^']+)'",
    re.DOTALL,
)


def iter_products() -> Iterable[dict[str, str]]:
    seen: set[str] = set()
    for path in DATA_FILES:
        if not path.exists():
            continue
        text = path.read_text(encoding="utf-8")
        for match in PRODUCT_PATTERN.finditer(text):
            item = match.groupdict()
            if item["id"] in seen:
                continue
            seen.add(item["id"])
            yield item


def select_image_url(html: str, page_url: str) -> str | None:
    soup = BeautifulSoup(html, "html.parser")
    selectors = [
        ('meta[property="og:image"]', "content"),
        ('meta[name="twitter:image"]', "content"),
        ('link[rel="image_src"]', "href"),
        ("img.BigImage", "src"),
        ("img#zoom_image", "src"),
        (".keyImg img", "src"),
        (".thumbnail img", "src"),
    ]
    for selector, attr in selectors:
        node = soup.select_one(selector)
        if node and node.get(attr):
            value = str(node.get(attr)).strip()
            if value and not value.startswith("data:"):
                return urljoin(page_url, value)
    return None


def download_image(session: requests.Session, image_url: str) -> Image.Image:
    response = session.get(image_url, timeout=TIMEOUT)
    response.raise_for_status()
    image = Image.open(io.BytesIO(response.content))
    image = ImageOps.exif_transpose(image).convert("RGBA")

    # Preserve transparency where available, otherwise place the product on white.
    if image.getextrema()[3] == (255, 255):
        image = image.convert("RGB")
    else:
        canvas = Image.new("RGBA", image.size, (255, 255, 255, 0))
        canvas.alpha_composite(image)
        image = canvas

    image.thumbnail((1200, 1200), Image.Resampling.LANCZOS)
    return image


def save_webp(image: Image.Image, destination: Path) -> None:
    destination.parent.mkdir(parents=True, exist_ok=True)
    image.save(destination, "WEBP", quality=88, method=6)


def js_string(value: str) -> str:
    return json.dumps(value, ensure_ascii=False)


def write_map(records: list[dict[str, str]]) -> None:
    lines = [
        "// Generated by guide/scripts/sync_product_images.py",
        "// Do not edit image paths manually; update the product URL and rerun the workflow.",
        "export const productImages={",
    ]
    for record in sorted(records, key=lambda item: item["id"]):
        lines.append(
            f"  {js_string(record['id'])}:{{"
            f"src:{js_string(record['src'])},"
            f"source:{js_string(record['source'])},"
            f"alt:{js_string(record['name'])}" 
            "},"
        )
    lines.append("};")
    lines.append("")
    OUTPUT_MAP.write_text("\n".join(lines), encoding="utf-8")


def main() -> int:
    products = list(iter_products())
    if not products:
        print("No product records found", file=sys.stderr)
        return 1

    OUTPUT_DIR.mkdir(parents=True, exist_ok=True)
    session = requests.Session()
    session.headers.update({
        "User-Agent": USER_AGENT,
        "Accept-Language": "ko-KR,ko;q=0.9,en;q=0.7",
    })

    records: list[dict[str, str]] = []
    failures: list[str] = []

    for index, product in enumerate(products, start=1):
        product_id = product["id"]
        destination = OUTPUT_DIR / f"{product_id}.webp"
        print(f"[{index}/{len(products)}] {product_id}")
        try:
            page = session.get(product["url"], timeout=TIMEOUT)
            page.raise_for_status()
            image_url = select_image_url(page.text, product["url"])
            if not image_url:
                raise RuntimeError("official product image was not found")
            image = download_image(session, image_url)
            save_webp(image, destination)
            records.append({
                "id": product_id,
                "name": product["name"],
                "src": f"./assets/products/{product_id}.webp",
                "source": image_url,
            })
        except Exception as exc:  # Keep a previously downloaded file usable.
            print(f"  warning: {exc}", file=sys.stderr)
            failures.append(product_id)
            if destination.exists():
                records.append({
                    "id": product_id,
                    "name": product["name"],
                    "src": f"./assets/products/{product_id}.webp",
                    "source": "",
                })

    write_map(records)
    print(f"Synced {len(records)} of {len(products)} product images")
    if failures:
        print("Failed: " + ", ".join(failures), file=sys.stderr)

    # A partial sync should still update successful and existing images.
    return 0 if records else 1


if __name__ == "__main__":
    raise SystemExit(main())
