(()=>{
  const SESSION='blueblack-admin-unlocked';
  const expected=String.fromCharCode(66,108,117,101,98,108,97,99,107,56,56,54,56);
  const style=document.createElement('style');
  style.textContent='.bb-admin-lock{position:fixed;inset:0;z-index:2147483647;display:grid;place-items:center;padding:22px;background:linear-gradient(135deg,#071629,#102b4c);font-family:Pretendard,-apple-system,BlinkMacSystemFont,"Segoe UI",sans-serif}.bb-admin-lock-card{width:min(420px,100%);padding:26px;border-radius:22px;background:#fff;box-shadow:0 24px 80px rgba(0,0,0,.28);color:#10233f}.bb-admin-lock-card small{display:block;color:#a77a3d;font-size:10px;font-weight:900}.bb-admin-lock-card h1{margin:8px 0}.bb-admin-lock-card p{color:#64758a;font-size:13px;line-height:1.7}.bb-admin-lock-card input{width:100%;height:52px;padding:0 14px;border:1px solid #ccd8e3;border-radius:13px;font-size:16px;box-sizing:border-box}.bb-admin-lock-card button{width:100%;height:52px;margin-top:10px;border:0;border-radius:13px;background:#102b4c;color:#fff;font-weight:900}.bb-admin-lock-error{min-height:20px;margin-top:10px;color:#b42318;font-size:12px;font-weight:800}';
  document.head.append(style);
  function injectInventory(){const grid=document.querySelector('.admin-tools-grid');if(!grid||grid.querySelector('[href="./inventory-audit/"]'))return;const card=document.createElement('a');card.className='admin-tool-card primary';card.href='./inventory-audit/';card.innerHTML='<span class="admin-tool-icon">▥</span><span class="admin-tool-copy"><small>INVENTORY AUDIT</small><h2>재고 조사</h2><p>구역을 선택하고 바코드를 스캔해 수량을 자동 집계하고 엑셀로 내려받습니다.</p></span><span class="admin-tool-arrow">→</span>';grid.append(card)}
  function showGate(){if(sessionStorage.getItem(SESSION)==='1')return;const gate=document.createElement('div');gate.className='bb-admin-lock';gate.innerHTML='<form class="bb-admin-lock-card" autocomplete="off"><small>BLUEBLACK PEN SHOP · ADMIN</small><h1>관리자 암호 확인</h1><p>매장 내부용 도구입니다. 암호를 입력하면 현재 브라우저 세션 동안 사용할 수 있습니다.</p><input type="password" placeholder="관리자 암호" autofocus><button type="submit">관리자 페이지 열기</button><div class="bb-admin-lock-error"></div></form>';gate.querySelector('form').onsubmit=e=>{e.preventDefault();const input=gate.querySelector('input'),error=gate.querySelector('.bb-admin-lock-error');if(input.value.trim()===expected){sessionStorage.setItem(SESSION,'1');gate.remove()}else{input.value='';input.focus();error.textContent='암호가 맞지 않습니다.'}};document.body.append(gate)}
  const init=()=>{injectInventory();showGate()};
  document.readyState==='loading'?document.addEventListener('DOMContentLoaded',init):init();
})();