import{API_URL,API_KEY}from'./audit-config.js';
const STORE='blueblack-inventory-audit-v1';
const $=s=>document.querySelector(s);
export const ui={area:$('#areaSelect'),custom:$('#customArea'),current:$('#currentArea'),sku:$('#skuCount'),units:$('#unitCount'),areaUnits:$('#areaUnitCount'),unknownCount:$('#unknownCount'),barcode:$('#barcodeInput'),addBarcode:$('#addBarcode'),status:$('#scanStatus'),latestEmpty:$('#latestEmpty'),latestCard:$('#latestCard'),latestMark:$('#latestMark'),latestBrand:$('#latestBrand'),latestName:$('#latestName'),latestMeta:$('#latestMeta'),latestQty:$('#latestQty'),areaSummary:$('#areaListSummary'),countList:$('#countList'),noBarcodeCount:$('#noBarcodeCount'),manualSearch:$('#manualSearch'),manualButton:$('#manualSearchButton'),manualResults:$('#manualResults'),unknownPanel:$('#unknownPanel'),unknownList:$('#unknownList'),modal:$('#candidateModal'),candidateList:$('#candidateList'),closeCandidate:$('#closeCandidate'),toast:$('#toast'),reset:$('#resetAudit'),exportTop:$('#exportTop'),exportExcel:$('#exportExcel')};
const fresh=()=>({startedAt:new Date().toISOString(),updatedAt:new Date().toISOString(),currentArea:'지하',counts:{},unknowns:{},latestKey:null});
export let state=(()=>{try{return{...fresh(),...JSON.parse(localStorage.getItem(STORE)||'{}')}}catch{return fresh()}})();
export const areaName=()=>String(state.currentArea||'').trim()||'미지정 구역';
export const productKey=p=>String(p.item_code||p.id||p.barcode||p.product_name);
export const esc=v=>String(v??'').replace(/[&<>'"]/g,c=>({'&':'&amp;','<':'&lt;','>':'&gt;',"'":'&#39;','"':'&quot;'}[c]));
export const numberText=v=>{const n=Number(v);return Number.isFinite(n)?n.toLocaleString('ko-KR'):'-'};
export const dateText=v=>{const d=new Date(v);return Number.isNaN(d.getTime())?'':new Intl.DateTimeFormat('ko-KR',{timeZone:'Asia/Seoul',year:'numeric',month:'2-digit',day:'2-digit',hour:'2-digit',minute:'2-digit'}).format(d)};
function changed(){document.dispatchEvent(new Event('audit:changed'))}
export function save(){state.updatedAt=new Date().toISOString();localStorage.setItem(STORE,JSON.stringify(state));changed()}
export function toast(message){ui.toast.textContent=message;ui.toast.classList.add('show');clearTimeout(toast.timer);toast.timer=setTimeout(()=>ui.toast.classList.remove('show'),2400)}
export function setStatus(message,type=''){ui.status.textContent=message;ui.status.className=`status ${type}`.trim()}
export async function rpc(name,body={}){const response=await fetch(`${API_URL}/rest/v1/rpc/${name}`,{method:'POST',headers:{apikey:API_KEY,Authorization:`Bearer ${API_KEY}`,'Content-Type':'application/json'},body:JSON.stringify(body)});const data=await response.json().catch(()=>null);if(!response.ok)throw new Error(data?.message||'상품 DB 요청에 실패했습니다.');return data}
function signal(ok=true){try{navigator.vibrate?.(ok?[45]:[90,50,90]);const c=new(window.AudioContext||window.webkitAudioContext)(),o=c.createOscillator(),g=c.createGain();o.frequency.value=ok?880:240;g.gain.value=.04;o.connect(g).connect(c.destination);o.start();o.stop(c.currentTime+.08)}catch{}}
export function addProduct(product,source='바코드'){const area=areaName(),key=`${area}::${productKey(product)}`,now=new Date().toISOString(),old=state.counts[key];state.counts[key]={...old,...product,area,barcode:product.barcode||'',qty:(old?.qty||0)+1,source:old?.source||source,firstAt:old?.firstAt||now,lastAt:now};state.latestKey=key;save();signal();setStatus(`${product.product_name} · ${area} ${(old?.qty||0)+1}개`,'ok');toast('수량이 1개 추가되었습니다.')}
export function addUnknown(code){const area=areaName(),key=`${area}::${code}`,now=new Date().toISOString(),old=state.unknowns[key];state.unknowns[key]={area,barcode:code,count:(old?.count||0)+1,firstAt:old?.firstAt||now,lastAt:now};save();signal(false);setStatus(`상품 DB에 없는 바코드입니다: ${code}`,'error');toast('등록되지 않은 바코드입니다.')}
export function setQuantity(key,value){const qty=Math.max(0,Math.floor(Number(value)||0));if(!state.counts[key])return;if(qty===0){delete state.counts[key];if(state.latestKey===key)state.latestKey=null}else{state.counts[key].qty=qty;state.counts[key].lastAt=new Date().toISOString()}save()}
export function setArea(value){state.currentArea=value;save()}
export function clearAudit(){state=fresh();localStorage.removeItem(STORE);changed()}
export function showCandidates(products){ui.candidateList.replaceChildren();products.forEach(product=>{const button=document.createElement('button');button.className='candidate';button.innerHTML=`<strong>${esc(product.product_name)}</strong><span>${esc([product.manufacturer,product.item_code&&`품목코드 ${product.item_code}`,`재고 ${numberText(product.stock_qty)}개`].filter(Boolean).join(' · '))}</span>`;button.onclick=()=>{ui.modal.hidden=true;addProduct(product)};ui.candidateList.append(button)});ui.modal.hidden=false}