import './public-ui-v52.js';
import './as-guide-i18n-v50.js?v=50';

const asCopy={
ko:{title:'A/S 안내',intro:'펜뷔페 전용 안내와 브랜드별 공식 접수처, 연락처, 주소와 비용 관련 주의사항을 확인할 수 있습니다.',search:'브랜드 검색',placeholder:'예: 라미, Lamy, 세일러, Sailor',shown:n=>`${n}개 접수처가 표시됩니다.`,empty:'일치하는 브랜드를 찾지 못했습니다.',penTitle:'펜뷔페 A/S·구매 안내',penIntro:'펜뷔페는 일반 브랜드 A/S와 별도의 블루블랙 전용 기준을 적용합니다.',nib:'펜촉',nibBody:'MF 단일촉으로 제공됩니다.',included:'기본 구성',includedBody:'블랙 색상 카트리지 2개가 동봉됩니다.',converter:'컨버터',converterBody:'기본 구성에 포함되지 않으며 별도 구매 상품입니다.',extra:'추가 색상 파츠',extraBody:'본품 구매 당일에 한해 추가 색상 파츠를 구매할 수 있습니다.',service:'전용 A/S',serviceBody:'블루블랙 펜샵에서만 가능하며 기한과 점검비는 없습니다. 부품 교체 시 비용이 발생합니다.',gift:'사은품 기준',giftBody:'펜뷔페 제품 금액은 사은품 합산 금액에서 제외됩니다.',openPen:'펜뷔페 미리보기',call:'전화 문의'},
en:{title:'After-Sales Service Guide',intro:'Review the Pen Buffet policy and official service centers, contacts, addresses and cost notices by brand.',search:'Search brand',placeholder:'e.g. Lamy, Sailor, Pilot, Parker',shown:n=>`${n} service centers shown.`,empty:'No matching brand was found.',penTitle:'Pen Buffet service & purchase guide',penIntro:'Pen Buffet products follow a separate BlueBlack service policy.',nib:'Nib',nibBody:'Available with an MF nib only.',included:'Included',includedBody:'Two black ink cartridges are included.',converter:'Converter',converterBody:'Not included and sold separately.',extra:'Additional color parts',extraBody:'Additional color parts may be purchased only on the same day as the main pen.',service:'Dedicated service',serviceBody:'Available only at BlueBlack Pen Shop with no time limit or inspection fee. Replacement parts may incur a charge.',gift:'Gift calculation',giftBody:'Pen Buffet purchases are excluded from the gift-amount calculation.',openPen:'Open Pen Buffet',call:'Call the store'},
ja:{title:'A/S・修理案内',intro:'ペンビュッフェ専用案内とブランド別の公式受付先、連絡先、住所、費用上の注意を確認できます。',search:'ブランド検索',placeholder:'例：ラミー、セーラー、パイロット',shown:n=>`${n}件の受付先を表示しています。`,empty:'該当するブランドがありません。',penTitle:'ペンビュッフェ A/S・購入案内',penIntro:'ペンビュッフェには一般ブランド修理とは別のBlueBlack専用基準があります。',nib:'ペン先',nibBody:'MFのみです。',included:'基本構成',includedBody:'ブラックのカートリッジ2本が付属します。',converter:'コンバーター',converterBody:'付属せず別売りです。',extra:'追加カラーパーツ',extraBody:'本体購入当日に限り追加パーツを購入できます。',service:'専用A/S',serviceBody:'BlueBlack Pen Shopのみで対応します。期限と点検費はありませんが、部品交換時は費用が発生します。',gift:'ノベルティ基準',giftBody:'ペンビュッフェ製品はノベルティ合算金額の対象外です。',openPen:'ペンビュッフェを開く',call:'店舗へ電話'},
'zh-Hans':{title:'售后服务指南',intro:'查看钢笔自助配色专用说明及各品牌官方受理中心、联系方式、地址和费用注意事项。',search:'搜索品牌',placeholder:'例如 Lamy、Sailor、Pilot、Parker',shown:n=>`显示${n}个受理中心。`,empty:'未找到匹配品牌。',penTitle:'钢笔自助配色售后与购买说明',penIntro:'钢笔自助配色产品适用BlueBlack专用服务标准。',nib:'笔尖',nibBody:'仅提供MF笔尖。',included:'基本配置',includedBody:'随附2支黑色墨囊。',converter:'上墨器',converterBody:'不包含，需另行购买。',extra:'追加颜色部件',extraBody:'仅限购买本体当天追加购买。',service:'专用售后',serviceBody:'仅限BlueBlack Pen Shop受理，不限期限且免检测费；更换部件时会产生费用。',gift:'赠品金额',giftBody:'Pen Buffet产品金额不计入赠品累计金额。',openPen:'打开配色预览',call:'致电门店'},
'zh-Hant':{title:'售後服務指南',intro:'查看鋼筆自助配色專用說明及各品牌官方受理中心、聯絡方式、地址與費用注意事項。',search:'搜尋品牌',placeholder:'例如 Lamy、Sailor、Pilot、Parker',shown:n=>`顯示${n}個受理中心。`,empty:'未找到符合品牌。',penTitle:'鋼筆自助配色售後與購買說明',penIntro:'鋼筆自助配色產品適用BlueBlack專用服務標準。',nib:'筆尖',nibBody:'僅提供MF筆尖。',included:'基本配置',includedBody:'隨附2支黑色墨囊。',converter:'吸墨器',converterBody:'不包含，需另行購買。',extra:'追加顏色部件',extraBody:'僅限購買本體當天追加購買。',service:'專用售後',serviceBody:'僅限BlueBlack Pen Shop受理，不限期限且免檢測費；更換部件時會產生費用。',gift:'贈品金額',giftBody:'Pen Buffet產品金額不計入贈品累計金額。',openPen:'開啟配色預覽',call:'致電門市'}
};
function asLang(){const raw=(new URLSearchParams(location.search).get('lang')||localStorage.getItem('blueblack-language')||navigator.language||'ko').toLowerCase();if(raw.includes('hant')||raw.startsWith('zh-tw')||raw.startsWith('zh-hk'))return'zh-Hant';if(raw.startsWith('zh'))return'zh-Hans';if(raw.startsWith('ja'))return'ja';if(raw.startsWith('en'))return'en';return'ko';}
function asNorm(value=''){return String(value).normalize('NFKC').toLowerCase().replace(/[^0-9a-z가-힣ぁ-んァ-ヶ一-龠]+/g,'');}
const input=document.querySelector('#asBrandSearch');
const clearButton=document.querySelector('#asBrandClear');
const summary=document.querySelector('#asResultSummary');
const cards=[...document.querySelectorAll('[data-as-search]')];
function installPenBuffetGuide(){const section=document.querySelector('.as-related');if(!section)return;section.id='pen-buffet-service';const finder=document.querySelector('#as-finder');finder?.before(section);section.className='detail-card as-precheck';}
function renderPenBuffetGuide(){const section=document.querySelector('#pen-buffet-service');if(!section)return;const t=asCopy[asLang()]||asCopy.ko;section.innerHTML=`<div class="as-section-heading"><div><small>PEN BUFFET SERVICE</small><h2>${t.penTitle}</h2></div><p>${t.penIntro}</p></div><div class="detail-grid"><article class="detail-item"><small>NIB</small><strong>${t.nib}</strong><span>${t.nibBody}</span></article><article class="detail-item"><small>INCLUDED</small><strong>${t.included}</strong><span>${t.includedBody}</span></article><article class="detail-item"><small>CONVERTER</small><strong>${t.converter}</strong><span>${t.converterBody}</span></article><article class="detail-item"><small>EXTRA PARTS</small><strong>${t.extra}</strong><span>${t.extraBody}</span></article><article class="detail-item"><small>A/S</small><strong>${t.service}</strong><span>${t.serviceBody}</span></article><article class="detail-item"><small>GIFT</small><strong>${t.gift}</strong><span>${t.giftBody}</span></article></div><div class="detail-actions"><a class="primary" href="../pen-buffet/" data-preserve-lang>${t.openPen}</a><a href="tel:027658868">${t.call}</a></div>`;}
function renderAs(){const term=asNorm(input?.value||'');let count=0;cards.forEach(card=>{const visible=!term||asNorm(card.dataset.asSearch).includes(term);card.hidden=!visible;if(visible)count+=1;});const t=asCopy[asLang()]||asCopy.ko;if(summary)summary.textContent=count?t.shown(count):t.empty;}
function applyAsLanguage(){const t=asCopy[asLang()]||asCopy.ko;document.querySelector('[data-as-title]')?.replaceChildren(t.title);document.querySelector('[data-as-intro]')?.replaceChildren(t.intro);document.querySelector('[data-as-search-label]')?.replaceChildren(t.search);if(input)input.placeholder=t.placeholder;document.title=t.title;renderPenBuffetGuide();renderAs();}
installPenBuffetGuide();
input?.addEventListener('input',renderAs);clearButton?.addEventListener('click',()=>{if(input){input.value='';renderAs();input.focus();}});document.querySelectorAll('[data-as-quick]').forEach(button=>button.addEventListener('click',()=>{if(input){input.value=button.dataset.asQuick||'';renderAs();input.focus({preventScroll:true});}}));document.querySelectorAll('[data-portal-lang]').forEach(button=>button.addEventListener('click',()=>queueMicrotask(applyAsLanguage)));applyAsLanguage();