export const parts = [
  {
    id: 'cap_body',
    nameKo: '캡',
    nameEn: 'Cap',
    nameJa: 'キャップ',
    descriptionKo: '클립과 캡 밴드가 장착되는 캡 본체입니다.',
    descriptionEn: 'The main cap body fitted with the clip and cap bands.',
    descriptionJa: 'クリップとキャップリングが付くキャップ本体です。',
    colorGroup: 'resin',
  },
  {
    id: 'cap_end',
    nameKo: '캡앤드',
    nameEn: 'Cap End',
    nameJa: 'キャップエンド',
    descriptionKo: '캡 끝을 마감하는 독립 파츠입니다.',
    descriptionEn: 'The separate end piece that finishes the top of the cap.',
    descriptionJa: 'キャップ上端を仕上げる独立パーツです。',
    colorGroup: 'resin',
  },
  {
    id: 'nib_grip',
    nameKo: '닙그립',
    nameEn: 'Nib Grip',
    nameJa: 'ペン先グリップ',
    descriptionKo: '닙과 피드를 고정하며 배럴에 결합되는 그립 파츠입니다.',
    descriptionEn: 'The grip section that holds the nib and feed and connects to the barrel.',
    descriptionJa: 'ペン先とペン芯を固定し、胴軸に接続するグリップパーツです。',
    colorGroup: 'resin',
  },
  {
    id: 'metal_parts',
    nameKo: '메탈파츠',
    nameEn: 'Metal Parts',
    nameJa: '金属パーツ',
    descriptionKo: '닙, 클립, 캡 밴드, 섹션 링 등 금속 파츠입니다.',
    descriptionEn: 'The nib, clip, cap bands, section ring and other metal fittings.',
    descriptionJa: 'ペン先、クリップ、キャップリング、首軸リングなどの金属パーツです。',
    colorGroup: 'metal',
  },
  {
    id: 'barrel_body',
    nameKo: '배럴',
    nameEn: 'Barrel',
    nameJa: '胴軸',
    descriptionKo: '잉크 카트리지 또는 컨버터를 감싸는 몸통 파츠입니다.',
    descriptionEn: 'The main body that houses an ink cartridge or optional converter.',
    descriptionJa: 'インクカートリッジまたは別売りコンバーターを収める胴軸です。',
    colorGroup: 'resin',
  },
  {
    id: 'barrel_end',
    nameKo: '배럴앤드',
    nameEn: 'Barrel End',
    nameJa: '胴軸エンド',
    descriptionKo: '배럴 끝을 마감하는 독립 파츠입니다.',
    descriptionEn: 'The separate end piece that finishes the back of the barrel.',
    descriptionJa: '胴軸後端を仕上げる独立パーツです。',
    colorGroup: 'resin',
  },
];

export const colors = [
  { id: 'clear', code: 'SE', nameKo: '세피아', nameEn: 'Sepia', nameJa: 'セピア', hex: '#4b4740', group: 'resin', transparent: true, transmission: 0.46, roughness: 0.1, attenuationDistance: 0.75, thickness: 1.35, isNew: false, market: 'KR' },
  { id: 'white', code: 'NI', nameKo: '나이트', nameEn: 'Night', nameJa: 'ナイト', hex: '#292b50', group: 'resin', transparent: true, transmission: 0.38, roughness: 0.1, attenuationDistance: 0.55, thickness: 1.4, isNew: false, market: 'KR' },
  { id: 'black', code: 'PC', nameKo: '피콕', nameEn: 'Peacock', nameJa: 'ピーコック', hex: '#167792', group: 'resin', transparent: true, transmission: 0.56, roughness: 0.08, attenuationDistance: 1.0, thickness: 1.25, isNew: false, market: 'KR' },
  { id: 'navy', code: 'ME', nameKo: '멜론', nameEn: 'Melon', nameJa: 'メロン', hex: '#8dce78', group: 'resin', transparent: true, transmission: 0.52, roughness: 0.1, attenuationDistance: 1.8, thickness: 1.2, isNew: false, market: 'KR' },
  { id: 'blue', code: 'CA', nameKo: '캐롯', nameEn: 'Carrot', nameJa: 'キャロット', hex: '#ed8435', group: 'resin', transparent: true, transmission: 0.58, roughness: 0.08, attenuationDistance: 1.2, thickness: 1.2, isNew: false, market: 'KR' },
  { id: 'sky', code: 'SU', nameKo: '썬플라워', nameEn: 'Sunflower', nameJa: 'サンフラワー', hex: '#f0c329', group: 'resin', transparent: true, transmission: 0.62, roughness: 0.08, attenuationDistance: 1.4, thickness: 1.18, isNew: false, market: 'KR' },
  { id: 'green', code: 'FL', nameKo: '플라밍고', nameEn: 'Flamingo', nameJa: 'フラミンゴ', hex: '#eca08f', group: 'resin', transparent: true, transmission: 0.44, roughness: 0.13, attenuationDistance: 1.3, thickness: 1.2, isNew: false, market: 'KR' },
  { id: 'yellow', code: 'WI', nameKo: '위스테리아', nameEn: 'Wisteria', nameJa: 'ウィステリア', hex: '#b9afd3', group: 'resin', transparent: true, transmission: 0.35, roughness: 0.18, attenuationDistance: 1.6, thickness: 1.25, isNew: false, market: 'KR' },
  { id: 'pink', code: 'LC', nameKo: '라벤더 캔디', nameEn: 'Lavender Candy', nameJa: 'ラベンダーキャンディ', hex: '#c9ddef', group: 'resin', transparent: true, transmission: 0.28, roughness: 0.22, attenuationDistance: 1.8, thickness: 1.25, isNew: false, market: 'KR' },
  { id: 'red', code: 'MI', nameKo: '밀크', nameEn: 'Milk', nameJa: 'ミルク', hex: '#f1f0e7', group: 'resin', transparent: true, transmission: 0.1, roughness: 0.26, attenuationDistance: 1.2, thickness: 1.3, isNew: false, market: 'KR' },
  { id: 'skeleton-flower', code: 'SF', nameKo: '스켈레톤 플라워', nameEn: 'Skeleton Flower', nameJa: 'スケルトンフラワー', hex: '#e1e1ec', group: 'resin', transparent: true, transmission: 0.78, roughness: 0.12, attenuationDistance: 3.5, thickness: 1.1, isNew: true, availableFrom: '2026-06-15', market: 'KR' },
  { id: 'rabbit', code: 'RB', nameKo: '래빗', nameEn: 'Rabbit', nameJa: 'ラビット', hex: '#bcafaf', group: 'resin', transparent: true, transmission: 0.28, roughness: 0.2, attenuationDistance: 1.5, thickness: 1.25, isNew: true, availableFrom: '2026-06-15', market: 'KR' },
  { id: 'sakuramochi', code: 'SM', nameKo: '사쿠라모찌', nameEn: 'Sakuramochi', nameJa: 'サクラモチ', hex: '#e5bdc8', group: 'resin', transparent: true, transmission: 0.32, roughness: 0.18, attenuationDistance: 1.6, thickness: 1.2, isNew: true, availableFrom: '2026-06-15', market: 'KR' },
  { id: 'strawberry', code: 'ST', nameKo: '스트로베리', nameEn: 'Strawberry', nameJa: 'ストロベリー', hex: '#c05b6b', group: 'resin', transparent: true, transmission: 0.48, roughness: 0.11, attenuationDistance: 0.9, thickness: 1.25, isNew: true, availableFrom: '2026-06-15', market: 'KR' },
  { id: 'apricot', code: 'AP', nameKo: '애프리콧', nameEn: 'Apricot', nameJa: 'アプリコット', hex: '#de9160', group: 'resin', transparent: true, transmission: 0.56, roughness: 0.09, attenuationDistance: 1.2, thickness: 1.2, isNew: true, availableFrom: '2026-06-15', market: 'KR' },
  { id: 'ginkgo-nuts', code: 'GI', nameKo: '징코 넛츠', nameEn: 'Ginkgo Nuts', nameJa: 'ギンコーナッツ', hex: '#d3b34c', group: 'resin', transparent: true, transmission: 0.56, roughness: 0.09, attenuationDistance: 1.2, thickness: 1.2, isNew: true, availableFrom: '2026-06-15', market: 'KR' },
  { id: 'jade', code: 'JD', nameKo: '제이드', nameEn: 'Jade', nameJa: 'ジェイド', hex: '#4e987b', group: 'resin', transparent: true, transmission: 0.52, roughness: 0.09, attenuationDistance: 1.0, thickness: 1.25, isNew: true, availableFrom: '2026-06-15', market: 'KR' },
  { id: 'sapphire', code: 'SP', nameKo: '사파이어', nameEn: 'Sapphire', nameJa: 'サファイア', hex: '#325ca6', group: 'resin', transparent: true, transmission: 0.44, roughness: 0.08, attenuationDistance: 0.7, thickness: 1.35, isNew: true, availableFrom: '2026-06-15', market: 'KR' },
  { id: 'akebia', code: 'AK', nameKo: '아케비아', nameEn: 'Akebia', nameJa: 'アケビア', hex: '#6f6581', group: 'resin', transparent: true, transmission: 0.36, roughness: 0.14, attenuationDistance: 0.85, thickness: 1.3, isNew: true, availableFrom: '2026-06-15', market: 'KR' },
  { id: 'wolf', code: 'WF', nameKo: '울프', nameEn: 'Wolf', nameJa: 'ウルフ', hex: '#68615e', group: 'resin', transparent: true, transmission: 0.34, roughness: 0.12, attenuationDistance: 0.65, thickness: 1.35, isNew: true, availableFrom: '2026-06-15', market: 'KR' },
  { id: 'silver', code: 'SV', nameKo: '실버', nameEn: 'Silver', nameJa: 'シルバー', hex: '#c8ccd1', group: 'metal', metalness: 0.92, roughness: 0.18, isNew: false, market: 'KR' },
  { id: 'gold', code: 'GD', nameKo: '골드', nameEn: 'Gold', nameJa: 'ゴールド', hex: '#d2ae62', group: 'metal', metalness: 0.9, roughness: 0.2, isNew: false, market: 'KR' },
];

export const defaultSelection = Object.fromEntries(parts.map((part) => [part.id, part.colorGroup === 'metal' ? 'silver' : 'clear']));
