export const parts = [
  {
    id: 'cap_body',
    nameKo: '캡',
    nameEn: 'Cap',
    nameJa: 'キャップ',
    descriptionKo: '펜을 닫았을 때 닙을 보호하는 상단 파츠입니다. 면적이 넓어 배럴과 함께 완성된 펜의 첫인상을 결정합니다.',
    descriptionEn: 'The upper part that protects the nib when the pen is closed. Together with the barrel, it defines the overall look of the finished pen.',
    descriptionJa: 'ペンを閉じたときにペン先を保護する上部パーツです。胴軸とともに、完成した万年筆の印象を大きく左右します。',
    colorGroup: 'resin',
  },
  {
    id: 'cap_end',
    nameKo: '캡앤드',
    nameEn: 'Cap End',
    nameJa: 'キャップエンド',
    descriptionKo: '캡 끝을 마감하는 작은 포인트 파츠입니다. 캡과 같은 색으로 자연스럽게 연결하거나 대비되는 색으로 포인트를 줄 수 있습니다.',
    descriptionEn: 'A small accent piece at the end of the cap. Match it with the cap for a seamless look, or choose a contrasting color for a clear accent.',
    descriptionJa: 'キャップ上端を仕上げる小さなアクセントパーツです。キャップと同色でまとめることも、対照色でポイントを加えることもできます。',
    colorGroup: 'resin',
  },
  {
    id: 'nib_grip',
    nameKo: '닙그립',
    nameEn: 'Nib Grip',
    nameJa: 'ペン先グリップ',
    descriptionKo: '글을 쓸 때 손가락이 닿는 그립 파츠입니다. 캡을 열었을 때 바로 보이는 부분이라 작은 색상 차이도 인상에 크게 영향을 줍니다.',
    descriptionEn: 'The grip section held while writing. Because it is immediately visible when the cap is removed, even a subtle color choice can change the pen’s character.',
    descriptionJa: '筆記時に指が触れるグリップパーツです。キャップを外すとすぐ見えるため、わずかな色の違いでも印象が大きく変わります。',
    colorGroup: 'resin',
  },
  {
    id: 'metal_parts',
    nameKo: '메탈파츠',
    nameEn: 'Metal Parts',
    nameJa: '金属パーツ',
    descriptionKo: '닙·클립·캡 밴드·링 등 금속 파츠의 색상을 실버 또는 골드로 선택합니다. 전체 조합의 분위기를 정리해주는 요소입니다.',
    descriptionEn: 'Choose silver or gold for the nib, clip, cap bands and rings. The metal finish brings the entire color combination together.',
    descriptionJa: 'ペン先・クリップ・キャップリングなどの金属パーツを、シルバーまたはゴールドから選びます。全体の配色を引き締める要素です。',
    colorGroup: 'metal',
  },
  {
    id: 'barrel_body',
    nameKo: '배럴',
    nameEn: 'Barrel',
    nameJa: '胴軸',
    descriptionKo: '손으로 잡는 몸통의 중심이 되는 파츠입니다. 가장 넓은 면적을 차지해 완성된 펜의 주된 색상을 결정합니다.',
    descriptionEn: 'The main body of the pen. As the largest visible resin part, it determines the dominant color of the finished design.',
    descriptionJa: '万年筆の胴体となる中心パーツです。見える面積が最も広く、完成したペンのメインカラーを決めます。',
    colorGroup: 'resin',
  },
  {
    id: 'barrel_end',
    nameKo: '배럴앤드',
    nameEn: 'Barrel End',
    nameJa: '胴軸エンド',
    descriptionKo: '배럴 끝을 마감하는 작은 포인트 파츠입니다. 캡앤드와 같은 색으로 맞추면 통일감을, 다른 색으로 고르면 개성을 더할 수 있습니다.',
    descriptionEn: 'A small accent piece at the end of the barrel. Match it with the cap end for balance, or choose a different color for a more distinctive finish.',
    descriptionJa: '胴軸後端を仕上げる小さなアクセントパーツです。キャップエンドと色を合わせると統一感が生まれ、異なる色にすると個性が際立ちます。',
    colorGroup: 'resin',
  },
];

export const colors = [
  { id: 'clear', code: 'SE', nameKo: '세피아', nameEn: 'Sepia', nameJa: 'セピア', hex: '#4b4740', group: 'resin', transparent: true, transmission: 0.46, roughness: 0.1, attenuationDistance: 0.75, thickness: 1.35, isNew: false, market: 'KR' },
  { id: 'white', code: 'NI', nameKo: '나이트', nameEn: 'Night', nameJa: 'ナイト', hex: '#292b50', group: 'resin', transparent: true, transmission: 0.38, roughness: 0.1, attenuationDistance: 0.55, thickness: 1.4, isNew: false, market: 'KR' },
  { id: 'black', code: 'PC', nameKo: '피콕', nameEn: 'Peacock', nameJa: 'ピーコック', hex: '#167792', group: 'resin', transparent: true, transmission: 0.56, roughness: 0.08, attenuationDistance: 1.0, thickness: 1.25, isNew: false, market: 'KR' },
  { id: 'navy', code: 'ME', nameKo: '멜론', nameEn: 'Melon', nameJa: 'メロン', hex: '#8dce78', group: 'resin', transparent: true, transmission: 0.52, roughness: 0.1, attenuationDistance: 1.8, thickness: 1.2, isNew: false, market: 'KR' },
  { id: 'blue', code: 'CA', nameKo: '캐롯', nameEn: 'Carrot', nameJa: 'キャロット', hex: '#ed8435', group: 'resin', transparent: true, transmission: 0.58, roughness: 0.08, attenuationDistance: 1.2, thickness: 1.2, isNew: false, market: 'KR' },
  { id: 'sky', code: 'SU', nameKo: '썬플라워', nameEn: 'Sunflower', nameJa: 'サンフラワー', hex: '#f0c329', group: 'resin', transparent: true, transmission: 0.62, roughness: 0.08, attenuationDistance: 1.4, thickness: 1.18, isNew: false, market: 'KR' },
  { id: 'green', code: 'FL', nameKo: '플라밍고', nameEn: 'Flamingo', nameJa: 'フラミンゴ', hex: '#eca08f', group: 'resin', transparent: true, transmission: 0.44, roughness: 0.13, attenuationDistance: 1.3, thickness: 1.2, isNew: false, market: 'KR' },
  { id: 'yellow', code: 'WI', nameKo: '위스테리아', nameEn: 'Wisteria', nameJa: 'ウィステリア', hex: '#b9afd3', group: 'resin', transparent: true, transmission: 0.35, roughness: 0.18, attenuationDistance: 1.6, thickness: 1.25, isNew: false, market: 'KR' },
  { id: 'pink', code: 'LC', nameKo: '라벤더 캔디', nameEn: 'Lavender Candy', nameJa: 'ラベンダーキャンディ', hex: '#c9ddef', group: 'resin', transparent: true, transmission: 0.28, roughness: 0.22, attenuationDistance: 1.8, thickness: 1.25, isNew: false, market: 'KR' },
  { id: 'red', code: 'MI', nameKo: '밀크', nameEn: 'Milk', nameJa: 'ミルク', hex: '#f1f0e7', group: 'resin', transparent: true, transmission: 0.1, roughness: 0.26, attenuationDistance: 1.2, thickness: 1.3, isNew: false, market: 'KR' },
  { id: 'skeleton-flower', code: 'SF', nameKo: '스켈레톤 플라워', nameEn: 'Skeleton Flower', nameJa: 'スケルトンフラワー', hex: '#e1e1ec', group: 'resin', transparent: true, transmission: 0.78, roughness: 0.12, attenuationDistance: 3.5, thickness: 1.1, isNew: true, availableFrom: '2026-06-15', market: 'KR' },
  { id: 'rabbit', code: 'RB', nameKo: '래빗', nameEn: 'Rabbit', nameJa: 'ラビット', hex: '#bcafaf', group: 'resin', transparent: true, transmission: 0.28, roughness: 0.2, attenuationDistance: 1.5, thickness: 1.25, isNew: true, availableFrom: '2026-06-15', market: 'KR' },
  { id: 'sakuramochi', code: 'SM', nameKo: '사쿠라모찌', nameEn: 'Sakuramochi', nameJa: 'サクラモチ', hex: '#e5bdc8', group: 'resin', transparent: true, transmission: 0.32, roughness: 0.18, attenuationDistance: 1.6, thickness: 1.2, isNew: true, availableFrom: '2026-06-15', market: 'KR' },
  { id: 'strawberry', code: 'ST', nameKo: '스트로베리', nameEn: 'Strawberry', nameJa: 'ストロベリー', hex: '#c05b6b', group: 'resin', transparent: true, transmission: 0.48, roughness: 0.11, attenuationDistance: 0.9, thickness: 1.25, isNew: true, availableFrom: '2026-06-15', market: 'KR' },
  { id: 'apricot', code: 'AP', nameKo: '애프리콧', nameEn: 'Apricot', nameJa: 'アプリコット', hex: '#de9160', group: 'resin', transparent: true, transmission: 0.56, roughness: 0.09, attenuationDistance: 1.2, thickness: 1.2, isNew: true, availableFrom: '2026-06-15', market: 'KR' },
  { id: 'ginkgo-nuts', code: 'GI', nameKo: '징코 넛츠', nameEn: 'Ginkgo Nuts', nameJa: 'ギンコーナッツ', hex: '#d3b34c', group: 'resin', transparent: true, transmission: 0.56, roughness: 0.09, attenuationDistance: 1.2, thickness: 1.2, isNew: true, availableFrom: '2026-06-15', market: 'KR' },
  { id: 'jade', code: 'JD', nameKo: '제이드', nameEn: 'Jade', nameJa: 'ジェイド', hex: '#4e987b', group: 'resin', transparent: true, transmission: 0.52, roughness: 0.09, attenuationDistance: 1.0, thickness: 1.25, isNew: true, availableFrom: '2026-06-15', market: 'KR' },
  { id: 'sapphire', code: 'SP', nameKo: '사파이어', nameEn: 'Sapphire', nameJa: 'サファイア', hex: '#325ca6', group: 'resin', transparent: true, transmission: 0.44, roughness: 0.08, attenuationDistance: 0.7, thickness: 1.35, isNew: true, availableFrom: '2026-06-15', market: 'KR' },
  { id: 'akebia', code: 'AK', nameKo: '아케비아', nameEn: 'Akebia', nameJa: 'アケビア', hex: '#6f6581', group: 'resin', transparent: true, transmission: 0.36, roughness: 0.14, attenuationDistance: 0.85, thickness: 1.3, isNew: true, availableFrom: '2026-06-15', market: 'KR' },
  { id: 'wolf', code: 'WF', nameKo: '울프', nameEn: 'Wolf', nameJa: 'ウルフ', hex: '#68615e', group: 'resin', transparent: true, transmission: 0.34, roughness: 0.12, attenuationDistance: 0.65, thickness: 1.35, isNew: true, availableFrom: '2026-06-15', market: 'KR' },
  { id: 'silver', code: 'SV', nameKo: '실버', nameEn: 'Silver', nameJa: 'シルバー', hex: '#c8ccd1', group: 'metal', metalness: 0.92, roughness: 0.18, isNew: false, market: 'KR' },
  { id: 'gold', code: 'GD', nameKo: '골드', nameEn: 'Gold', nameJa: 'ゴールド', hex: '#d2ae62', group: 'metal', metalness: 0.9, roughness: 0.2, isNew: false, market: 'KR' },
];

export const defaultSelection = Object.fromEntries(parts.map((part) => [part.id, part.colorGroup === 'metal' ? 'silver' : 'clear']));
