const LANGS=['ko','en','ja','zh-Hans','zh-Hant'];
const COPY={
ko:{pageTitle:'각인 안내',pageIntro:'공식 안내에 등록된 12가지 글꼴과 지원 문자를 확인하고, 각인 문구를 직원과 함께 최종 점검해 보세요.',sourceTitle:'블루블랙 공식 각인 안내 기준',sourceBody:'공식 페이지에서 확인되는 글꼴명, 지원 문자와 필기체 주의사항을 매장 상담용으로 정리했습니다.',openOfficial:'공식 샘플 보기',factsTitle:'공식 페이지에서 확인된 내용',factsBody:'공식 페이지에는 총 12가지 글꼴과 각 글꼴이 지원하는 문자 종류가 안내되어 있습니다.',fontCountTitle:'각인 글꼴',fontCountBody:'돋움부터 모노타입까지 12가지 선택지가 있습니다.',scriptTitle:'지원 문자 종류',scriptBody:'한글, 한문, 영어, 숫자 지원 여부가 글꼴마다 다릅니다.',cursiveTitle:'필기체 주의',cursiveBody:'필기체는 영어와 숫자를 지원하지만 연속 대문자는 사용할 수 없습니다.',finderTitle:'각인 글꼴 찾기',finderBody:'각인하려는 문자 종류를 선택하면 사용할 수 있는 글꼴만 볼 수 있습니다.',previewLabel:'미리 볼 문구',previewHelp:'화면 미리보기는 글꼴 분위기 참고용입니다. 실제 각인 형태는 공식 샘플과 완성품을 기준으로 확인해 주세요.',flowTitle:'각인 전 확인 순서',flowBody:'아래 순서는 매장 상담을 빠르게 진행하기 위한 확인 흐름입니다.',step1Title:'제품 확인',step1Body:'선택한 제품의 각인 가능 여부와 위치를 직원에게 확인합니다.',step2Title:'글꼴 선택',step2Body:'입력할 문자 종류를 지원하는 글꼴을 선택합니다.',step3Title:'문구 확인',step3Body:'철자, 띄어쓰기, 대문자와 소문자를 그대로 확인합니다.',step4Title:'최종 확인',step4Body:'직원과 각인 내용 및 제품별 적용 가능 여부를 최종 확인합니다.',cautionTitle:'꼭 확인해 주세요',caution1:'공식 페이지에는 가격, 글자 수, 소요 기간이 별도로 안내되어 있지 않습니다.',caution2:'제품마다 각인 가능 여부와 위치가 다를 수 있으므로 직원 확인이 우선입니다.',caution3:'각인 전 철자와 대소문자를 신중하게 확인해 주세요.',caution4:'필기체는 연속 대문자를 사용할 수 없습니다.',officialButton:'공식 글꼴 샘플 보기',callStore:'매장 전화 문의',all:'전체',hangul:'한글',hanja:'한문',latin:'영어',number:'숫자',result:n=>`${n}개 글꼴이 표시됩니다.`,cursiveNote:'연속 대문자 불가',empty:'해당 문자를 지원하는 글꼴이 없습니다.'},
en:{pageTitle:'Engraving Guide',pageIntro:'Review the 12 official font options and supported characters, then confirm the final engraving text with store staff.',sourceTitle:'Based on BlueBlack official engraving information',sourceBody:'Font names, supported characters and the cursive-capital restriction are organized from the official page for in-store consultation.',openOfficial:'View official samples',factsTitle:'Confirmed official information',factsBody:'The official page lists 12 fonts and the character sets supported by each font.',fontCountTitle:'Engraving fonts',fontCountBody:'Twelve options are listed, from Dotum to Monotype.',scriptTitle:'Character sets',scriptBody:'Support for Korean, Chinese characters, English and numbers differs by font.',cursiveTitle:'Cursive restriction',cursiveBody:'Cursive supports English and numbers, but consecutive capital letters are unavailable.',finderTitle:'Find an engraving font',finderBody:'Choose the characters you need to see compatible fonts.',previewLabel:'Preview text',previewHelp:'The on-screen preview only suggests the style. Check the official samples and finished product for the exact appearance.',flowTitle:'Before engraving',flowBody:'Use this flow to make the in-store consultation faster.',step1Title:'Check the product',step1Body:'Ask staff whether the selected product can be engraved and where.',step2Title:'Choose a font',step2Body:'Choose a font that supports the characters in your text.',step3Title:'Check the text',step3Body:'Confirm spelling, spacing and capitalization exactly as entered.',step4Title:'Final confirmation',step4Body:'Confirm the final text and product eligibility with staff.',cautionTitle:'Please note',caution1:'The official page does not separately list price, character limits or processing time.',caution2:'Engraving availability and position may differ by product; staff confirmation takes priority.',caution3:'Carefully verify spelling and capitalization before engraving.',caution4:'Consecutive capital letters are unavailable in the cursive font.',officialButton:'View official font samples',callStore:'Call the store',all:'All',hangul:'Korean',hanja:'Chinese characters',latin:'English',number:'Numbers',result:n=>`${n} fonts shown.`,cursiveNote:'No consecutive capitals',empty:'No font supports that character set.'},
ja:{pageTitle:'名入れ案内',pageIntro:'公式案内の12種類のフォントと対応文字を確認し、名入れ内容をスタッフと最終確認してください。',sourceTitle:'BlueBlack公式名入れ案内に基づく情報',sourceBody:'公式ページのフォント名、対応文字、筆記体の注意事項を店頭用に整理しました。',openOfficial:'公式サンプルを見る',factsTitle:'公式ページで確認できる内容',factsBody:'公式ページには12種類のフォントと各フォントの対応文字が案内されています。',fontCountTitle:'名入れフォント',fontCountBody:'돋움からモノタイプまで12種類あります。',scriptTitle:'対応文字',scriptBody:'韓国語、漢字、英語、数字の対応はフォントごとに異なります。',cursiveTitle:'筆記体の注意',cursiveBody:'筆記体は英語と数字に対応しますが、大文字の連続は使用できません。',finderTitle:'フォントを探す',finderBody:'使用する文字を選ぶと対応フォントのみ表示します。',previewLabel:'プレビュー文字',previewHelp:'画面表示は雰囲気の参考です。正確な形は公式サンプルと完成品で確認してください。',flowTitle:'名入れ前の確認順序',flowBody:'店頭相談をスムーズにするための確認手順です。',step1Title:'商品確認',step1Body:'商品が名入れ可能か、位置はどこかをスタッフに確認します。',step2Title:'フォント選択',step2Body:'入力文字に対応するフォントを選びます。',step3Title:'文字確認',step3Body:'スペル、空白、大文字・小文字をそのまま確認します。',step4Title:'最終確認',step4Body:'内容と商品への適用可否をスタッフと最終確認します。',cautionTitle:'必ずご確認ください',caution1:'公式ページには価格、文字数、所要時間の記載がありません。',caution2:'商品により可否と位置が異なるため、スタッフ確認が優先です。',caution3:'名入れ前にスペルと大文字・小文字を慎重に確認してください。',caution4:'筆記体は大文字を連続して使用できません。',officialButton:'公式フォントサンプル',callStore:'店舗へ電話',all:'すべて',hangul:'韓国語',hanja:'漢字',latin:'英語',number:'数字',result:n=>`${n}種類を表示しています。`,cursiveNote:'大文字の連続不可',empty:'対応するフォントがありません。'},
'zh-Hans':{pageTitle:'刻字指南',pageIntro:'查看官方列出的12种字体及支持字符，并与店员最终确认刻字内容。',sourceTitle:'依据BlueBlack官方刻字说明',sourceBody:'本页整理了官方页面中的字体名称、支持字符和手写体注意事项。',openOfficial:'查看官方示例',factsTitle:'官网确认信息',factsBody:'官方网站列出12种字体以及每种字体支持的字符类型。',fontCountTitle:'刻字字体',fontCountBody:'从Dotum到Monotype共有12种选择。',scriptTitle:'支持字符',scriptBody:'韩文、汉字、英文和数字的支持情况因字体而异。',cursiveTitle:'手写体注意事项',cursiveBody:'手写体支持英文和数字，但不能连续使用大写字母。',finderTitle:'查找刻字字体',finderBody:'选择需要使用的字符类型，仅显示兼容字体。',previewLabel:'预览文字',previewHelp:'屏幕预览仅供风格参考，请以官方示例和成品为准。',flowTitle:'刻字前确认顺序',flowBody:'以下流程用于加快门店咨询。',step1Title:'确认产品',step1Body:'向店员确认所选产品是否可刻字及刻字位置。',step2Title:'选择字体',step2Body:'选择支持所需字符的字体。',step3Title:'核对文字',step3Body:'准确核对拼写、空格及大小写。',step4Title:'最终确认',step4Body:'与店员最终确认刻字内容和产品适用情况。',cautionTitle:'请务必确认',caution1:'官方页面未单独说明价格、字数限制或处理时间。',caution2:'不同产品的可刻字情况和位置可能不同，以店员确认为准。',caution3:'刻字前请仔细核对拼写和大小写。',caution4:'手写体不能连续使用大写字母。',officialButton:'查看官方字体示例',callStore:'致电门店',all:'全部',hangul:'韩文',hanja:'汉字',latin:'英文',number:'数字',result:n=>`显示${n}种字体。`,cursiveNote:'不可连续大写',empty:'没有支持该字符的字体。'},
'zh-Hant':{pageTitle:'刻字指南',pageIntro:'查看官方列出的12種字體及支援字元，並與店員最終確認刻字內容。',sourceTitle:'依據BlueBlack官方刻字說明',sourceBody:'本頁整理官方頁面中的字體名稱、支援字元與手寫體注意事項。',openOfficial:'查看官方範例',factsTitle:'官網確認資訊',factsBody:'官方網站列出12種字體以及每種字體支援的字元類型。',fontCountTitle:'刻字字體',fontCountBody:'從Dotum到Monotype共有12種選擇。',scriptTitle:'支援字元',scriptBody:'韓文、漢字、英文與數字的支援情況因字體而異。',cursiveTitle:'手寫體注意事項',cursiveBody:'手寫體支援英文與數字，但不能連續使用大寫字母。',finderTitle:'查找刻字字體',finderBody:'選擇需要使用的字元類型，只顯示相容字體。',previewLabel:'預覽文字',previewHelp:'畫面預覽僅供風格參考，請以官方範例與成品為準。',flowTitle:'刻字前確認順序',flowBody:'以下流程用於加快門市諮詢。',step1Title:'確認產品',step1Body:'向店員確認所選產品是否可刻字及刻字位置。',step2Title:'選擇字體',step2Body:'選擇支援所需字元的字體。',step3Title:'核對文字',step3Body:'準確核對拼字、空格及大小寫。',step4Title:'最終確認',step4Body:'與店員最終確認刻字內容與產品適用情況。',cautionTitle:'請務必確認',caution1:'官方頁面未單獨說明價格、字數限制或處理時間。',caution2:'不同產品的可刻字情況與位置可能不同，以店員確認為準。',caution3:'刻字前請仔細核對拼字與大小寫。',caution4:'手寫體不能連續使用大寫字母。',officialButton:'查看官方字體範例',callStore:'致電門市',all:'全部',hangul:'韓文',hanja:'漢字',latin:'英文',number:'數字',result:n=>`顯示${n}種字體。`,cursiveNote:'不可連續大寫',empty:'沒有支援該字元的字體。'}
};
const FONTS=[
{id:1,name:'돋움',scripts:['hangul','hanja','latin','number'],style:'font-sans'},
{id:2,name:'바탕',scripts:['hangul','hanja','latin','number'],style:'font-serif'},
{id:3,name:'휴먼편지',scripts:['hangul','hanja','latin','number'],style:'font-letter'},
{id:4,name:'난초',scripts:['hangul','latin','number'],style:'font-brush'},
{id:5,name:'나눔고딕',scripts:['hangul','latin','number'],style:'font-sans'},
{id:6,name:'나눔붓',scripts:['hangul','latin','number'],style:'font-brush'},
{id:7,name:'잉크버로우',scripts:['latin','number'],style:'font-letter'},
{id:8,name:'필기체',scripts:['latin','number'],style:'font-script',note:true},
{id:9,name:'브래들리',scripts:['latin','number'],style:'font-letter'},
{id:10,name:'반흘림',scripts:['hangul','latin','number'],style:'font-brush'},
{id:11,name:'해서',scripts:['hangul','hanja','latin','number'],style:'font-serif'},
{id:12,name:'모노타입',scripts:['latin','number'],style:'font-mono'}
];
function normalizeLang(value=''){const v=String(value).toLowerCase();if(v.includes('hant')||v.startsWith('zh-tw')||v.startsWith('zh-hk'))return'zh-Hant';if(v.startsWith('zh'))return'zh-Hans';if(v.startsWith('ja'))return'ja';if(v.startsWith('en'))return'en';return'ko';}
function currentLang(){const query=new URLSearchParams(location.search).get('lang');return normalizeLang(query||localStorage.getItem('blueblack-language')||navigator.language);}
let lang=currentLang();let filter='all';
const grid=document.querySelector('#engravingFontGrid');const controls=document.querySelector('#engravingFilter');const input=document.querySelector('#engravingPreviewText');const summary=document.querySelector('#engravingResultSummary');
function t(){return COPY[lang]||COPY.ko;}
function renderControls(){const labels=['all','hangul','hanja','latin','number'];controls.innerHTML='';labels.forEach(key=>{const button=document.createElement('button');button.type='button';button.dataset.filter=key;button.textContent=t()[key];button.setAttribute('aria-pressed',String(filter===key));button.addEventListener('click',()=>{filter=key;renderControls();renderFonts();});controls.append(button);});}
function renderFonts(){const text=input.value.trim()||'BlueBlack 2026';const items=FONTS.filter(font=>filter==='all'||font.scripts.includes(filter));summary.textContent=t().result(items.length);grid.innerHTML='';if(!items.length){grid.innerHTML=`<div class="engraving-empty">${t().empty}</div>`;return;}items.forEach(font=>{const card=document.createElement('article');card.className=`engraving-font-card ${font.style}`;card.innerHTML=`<div class="engraving-font-head"><div><strong>${font.name}</strong></div><b>${String(font.id).padStart(2,'0')}</b></div>${font.note?`<em>${t().cursiveNote}</em>`:''}<div class="engraving-preview">${text.replace(/[&<>"']/g,ch=>({'&':'&amp;','<':'&lt;','>':'&gt;','"':'&quot;',"'":'&#39;'}[ch]))}</div><div class="engraving-support">${font.scripts.map(key=>`<span>${t()[key]}</span>`).join('')}</div>`;grid.append(card);});}
function applyLanguage(){lang=currentLang();document.documentElement.lang=lang;document.querySelectorAll('[data-engraving-t]').forEach(node=>{const value=t()[node.dataset.engravingT];if(typeof value==='string')node.textContent=value;});document.title=t().pageTitle;renderControls();renderFonts();}
input?.addEventListener('input',renderFonts);document.querySelectorAll('[data-portal-lang]').forEach(button=>button.addEventListener('click',()=>queueMicrotask(applyLanguage)));applyLanguage();
