const COPY={
ko:{pageTitle:'각인 안내',pageIntro:'각인 방식과 비용, 12가지 글꼴과 지원 문자를 확인하고 직원과 최종 점검해 보세요.',sourceTitle:'블루블랙 각인 안내',sourceBody:'공식 페이지의 글꼴·지원 문자 정보와 매장 각인 비용 기준을 상담용으로 정리했습니다.',openOfficial:'공식 글꼴 샘플',factsTitle:'공식 페이지에서 확인된 내용',factsBody:'공식 페이지에는 총 12가지 글꼴과 각 글꼴이 지원하는 문자 종류가 안내되어 있습니다.',fontCountTitle:'각인 글꼴',fontCountBody:'돋움부터 모노타입까지 12가지 선택지가 있습니다.',scriptTitle:'지원 문자 종류',scriptBody:'한글, 한문, 영어, 숫자 지원 여부가 글꼴마다 다릅니다.',cursiveTitle:'필기체 주의',cursiveBody:'필기체는 영어와 숫자를 지원하지만 연속 대문자는 사용할 수 없습니다.',finderTitle:'각인 글꼴 찾기',finderBody:'각인하려는 문자 종류를 선택하면 사용할 수 있는 글꼴만 볼 수 있습니다.',previewLabel:'미리 볼 문구',previewHelp:'화면 미리보기는 분위기 참고용입니다. 실제 결과는 공식 샘플과 완성품을 기준으로 확인해 주세요.',flowTitle:'각인 전 확인 순서',flowBody:'아래 순서대로 확인하면 매장 상담을 빠르게 진행할 수 있습니다.',step1Title:'제품 확인',step1Body:'제품의 각인 가능 여부와 위치를 직원에게 확인합니다.',step2Title:'방식·글꼴 선택',step2Body:'레이저 또는 조각 방식과 지원 글꼴을 선택합니다.',step3Title:'문구 확인',step3Body:'철자, 띄어쓰기, 대문자와 소문자를 그대로 확인합니다.',step4Title:'일정·비용 확인',step4Body:'당일 여부와 추가 비용을 포함해 최종 금액을 확인합니다.',cautionTitle:'꼭 확인해 주세요',caution1:'레이저 각인은 3,500원, 조각 각인은 5,000원입니다.',caution2:'당일 각인은 선택한 방식의 기본 비용에 1,000원이 추가됩니다.',caution3:'제품마다 각인 가능 여부와 위치가 다를 수 있으므로 직원 확인이 우선입니다.',caution4:'필기체는 연속 대문자를 사용할 수 없습니다.',officialButton:'공식 글꼴 샘플 보기',callStore:'매장 전화 문의',all:'전체',hangul:'한글',hanja:'한문',latin:'영어',number:'숫자',result:n=>`${n}개 글꼴이 표시됩니다.`,cursiveNote:'연속 대문자 불가',empty:'해당 문자를 지원하는 글꼴이 없습니다.',serviceTitle:'각인 방식과 비용',serviceIntro:'당일 작업은 선택한 각인 방식의 기본 비용에 1,000원이 추가됩니다.',laser:'레이저 각인',laserBody:'표면에 레이저로 문구를 새기는 방식',carving:'조각 각인',carvingBody:'문구를 물리적으로 파내어 새기는 방식',sameDay:'당일 추가',sameDayBody:'기본 비용에 추가',laserToday:'레이저 당일 총액',carvingToday:'조각 당일 총액',scope:'제품별 소재와 형태에 따라 가능한 방식·위치가 다를 수 있습니다.'},
en:{pageTitle:'Engraving Guide',pageIntro:'Review engraving methods, prices, 12 fonts and supported characters, then confirm with staff.',sourceTitle:'BlueBlack engraving guide',sourceBody:'Official font information and in-store engraving prices are organized for consultation.',openOfficial:'Official font samples',factsTitle:'Official font information',factsBody:'The official page lists 12 fonts and supported character sets.',fontCountTitle:'Engraving fonts',fontCountBody:'Twelve options are available.',scriptTitle:'Character sets',scriptBody:'Korean, Chinese characters, English and number support varies by font.',cursiveTitle:'Cursive restriction',cursiveBody:'Cursive supports English and numbers, but consecutive capitals are unavailable.',finderTitle:'Find a font',finderBody:'Choose a character set to view compatible fonts.',previewLabel:'Preview text',previewHelp:'The preview is illustrative. Confirm the exact result with official samples and the finished item.',flowTitle:'Before engraving',flowBody:'Follow these steps for a faster consultation.',step1Title:'Check the product',step1Body:'Confirm eligibility and engraving position with staff.',step2Title:'Choose method and font',step2Body:'Choose laser or carved engraving and a compatible font.',step3Title:'Check the text',step3Body:'Confirm spelling, spacing and capitalization.',step4Title:'Confirm timing and price',step4Body:'Confirm the total including any same-day surcharge.',cautionTitle:'Please note',caution1:'Laser engraving is KRW 3,500 and carved engraving is KRW 5,000.',caution2:'Same-day service adds KRW 1,000 to the selected base price.',caution3:'Available methods and positions vary by product.',caution4:'Consecutive capitals are unavailable in cursive.',officialButton:'Official font samples',callStore:'Call the store',all:'All',hangul:'Korean',hanja:'Chinese characters',latin:'English',number:'Numbers',result:n=>`${n} fonts shown.`,cursiveNote:'No consecutive capitals',empty:'No compatible font.',serviceTitle:'Engraving methods and prices',serviceIntro:'Same-day service adds KRW 1,000 to the selected method.',laser:'Laser engraving',laserBody:'The text is marked onto the surface with a laser.',carving:'Carved engraving',carvingBody:'The text is physically cut into the surface.',sameDay:'Same-day surcharge',sameDayBody:'Added to the base price',laserToday:'Same-day laser total',carvingToday:'Same-day carved total',scope:'Available methods and positions may vary by material and product shape.'},
ja:{pageTitle:'名入れ案内',pageIntro:'名入れ方法、料金、12種類のフォントと対応文字を確認できます。',sourceTitle:'BlueBlack名入れ案内',sourceBody:'公式フォント情報と店頭料金基準を整理しました。',openOfficial:'公式フォントサンプル',factsTitle:'公式フォント情報',factsBody:'公式ページには12種類のフォントと対応文字が案内されています。',fontCountTitle:'名入れフォント',fontCountBody:'12種類から選択できます。',scriptTitle:'対応文字',scriptBody:'韓国語、漢字、英語、数字の対応はフォントごとに異なります。',cursiveTitle:'筆記体の注意',cursiveBody:'英語と数字に対応しますが、大文字の連続はできません。',finderTitle:'フォントを探す',finderBody:'文字種類を選ぶと対応フォントを表示します。',previewLabel:'プレビュー文字',previewHelp:'画面表示は参考用です。正確な結果は公式サンプルと完成品で確認してください。',flowTitle:'名入れ前の確認',flowBody:'次の順序で確認してください。',step1Title:'商品確認',step1Body:'名入れ可否と位置を確認します。',step2Title:'方法・フォント選択',step2Body:'レーザーまたは彫刻とフォントを選びます。',step3Title:'文字確認',step3Body:'スペル、空白、大文字・小文字を確認します。',step4Title:'日程・料金確認',step4Body:'当日追加料金を含む合計を確認します。',cautionTitle:'ご確認ください',caution1:'レーザー刻印は3,500ウォン、彫刻刻印は5,000ウォンです。',caution2:'当日対応は基本料金に1,000ウォン追加です。',caution3:'商品により方法と位置が異なります。',caution4:'筆記体は大文字の連続不可です。',officialButton:'公式フォントサンプル',callStore:'店舗へ電話',all:'すべて',hangul:'韓国語',hanja:'漢字',latin:'英語',number:'数字',result:n=>`${n}種類を表示しています。`,cursiveNote:'大文字の連続不可',empty:'対応フォントがありません。',serviceTitle:'名入れ方法と料金',serviceIntro:'当日対応は選択した方法の基本料金に1,000ウォン追加です。',laser:'レーザー刻印',laserBody:'レーザーで表面に文字を刻印する方式',carving:'彫刻刻印',carvingBody:'表面を物理的に削って文字を刻む方式',sameDay:'当日追加',sameDayBody:'基本料金に追加',laserToday:'レーザー当日合計',carvingToday:'彫刻当日合計',scope:'素材や形状により対応方法・位置が異なる場合があります。'},
'zh-Hans':{pageTitle:'刻字指南',pageIntro:'查看刻字方式、费用、12种字体及支持字符。',sourceTitle:'BlueBlack刻字指南',sourceBody:'整理官网字体信息和门店刻字费用。',openOfficial:'官方字体示例',factsTitle:'官方字体信息',factsBody:'官网列出12种字体及支持字符。',fontCountTitle:'刻字字体',fontCountBody:'共有12种选择。',scriptTitle:'支持字符',scriptBody:'韩文、汉字、英文和数字因字体而异。',cursiveTitle:'手写体注意',cursiveBody:'支持英文和数字，但不能连续大写。',finderTitle:'查找字体',finderBody:'选择字符类型查看兼容字体。',previewLabel:'预览文字',previewHelp:'屏幕预览仅供参考，请以官方示例和成品为准。',flowTitle:'刻字前确认',flowBody:'请按以下顺序确认。',step1Title:'确认产品',step1Body:'确认是否可刻字及位置。',step2Title:'选择方式与字体',step2Body:'选择激光或雕刻方式及字体。',step3Title:'核对文字',step3Body:'核对拼写、空格和大小写。',step4Title:'确认时间与费用',step4Body:'确认含当日附加费的总额。',cautionTitle:'请注意',caution1:'激光刻字3,500韩元，雕刻刻字5,000韩元。',caution2:'当日服务在基本费用上加收1,000韩元。',caution3:'不同商品可用方式和位置可能不同。',caution4:'手写体不可连续大写。',officialButton:'官方字体示例',callStore:'致电门店',all:'全部',hangul:'韩文',hanja:'汉字',latin:'英文',number:'数字',result:n=>`显示${n}种字体。`,cursiveNote:'不可连续大写',empty:'没有兼容字体。',serviceTitle:'刻字方式与费用',serviceIntro:'当日服务在所选方式的基本费用上加收1,000韩元。',laser:'激光刻字',laserBody:'使用激光在表面标记文字',carving:'雕刻刻字',carvingBody:'在表面物理刻入文字',sameDay:'当日附加费',sameDayBody:'加在基本费用上',laserToday:'激光当日总额',carvingToday:'雕刻当日总额',scope:'可用方式和位置可能因材质与形状而异。'},
'zh-Hant':{pageTitle:'刻字指南',pageIntro:'查看刻字方式、費用、12種字體及支援字元。',sourceTitle:'BlueBlack刻字指南',sourceBody:'整理官網字體資訊與門市刻字費用。',openOfficial:'官方字體範例',factsTitle:'官方字體資訊',factsBody:'官網列出12種字體及支援字元。',fontCountTitle:'刻字字體',fontCountBody:'共有12種選擇。',scriptTitle:'支援字元',scriptBody:'韓文、漢字、英文與數字因字體而異。',cursiveTitle:'手寫體注意',cursiveBody:'支援英文與數字，但不能連續大寫。',finderTitle:'查找字體',finderBody:'選擇字元類型查看相容字體。',previewLabel:'預覽文字',previewHelp:'畫面預覽僅供參考，請以官方範例與成品為準。',flowTitle:'刻字前確認',flowBody:'請按以下順序確認。',step1Title:'確認產品',step1Body:'確認是否可刻字及位置。',step2Title:'選擇方式與字體',step2Body:'選擇雷射或雕刻方式及字體。',step3Title:'核對文字',step3Body:'核對拼字、空格與大小寫。',step4Title:'確認時間與費用',step4Body:'確認含當日附加費的總額。',cautionTitle:'請注意',caution1:'雷射刻字3,500韓元，雕刻刻字5,000韓元。',caution2:'當日服務在基本費用上加收1,000韓元。',caution3:'不同商品可用方式與位置可能不同。',caution4:'手寫體不可連續大寫。',officialButton:'官方字體範例',callStore:'致電門市',all:'全部',hangul:'韓文',hanja:'漢字',latin:'英文',number:'數字',result:n=>`顯示${n}種字體。`,cursiveNote:'不可連續大寫',empty:'沒有相容字體。',serviceTitle:'刻字方式與費用',serviceIntro:'當日服務在所選方式的基本費用上加收1,000韓元。',laser:'雷射刻字',laserBody:'使用雷射在表面標記文字',carving:'雕刻刻字',carvingBody:'在表面物理刻入文字',sameDay:'當日附加費',sameDayBody:'加在基本費用上',laserToday:'雷射當日總額',carvingToday:'雕刻當日總額',scope:'可用方式與位置可能因材質與形狀而異。'}
};
const FONTS=[
{id:1,name:'돋움',scripts:['hangul','hanja','latin','number'],style:'font-sans'},
{id:2,name:'바탕',scripts:['hangul','hanja','latin','number'],style:'font-serif'},
{id:3,name:'휴먼편지',scripts:['hangul','hanja','latin','number'],style:'font-letter'},
{id:4,name:'난초',scripts:['hangul','latin','number'],style:'font-brush'},
{id:5,name:'나눔고딕',scripts:['hangul','latin','number'],style:'font-sans'},
{id:6,name:'나눔붓',scripts:['hangul','latin','number'],style:'font-brush'},
{id:7,name:'잉크버로우',scripts:['latin','number'],style:'font-letter'},
{id:8,name:'필기체',scripts:['latin','number'],style:'font-script',note:true},
{id:9,name:'브래들리',scripts:['latin','number'],style:'font-letter'},
{id:10,name:'반흘림',scripts:['hangul','latin','number'],style:'font-brush'},
{id:11,name:'해서',scripts:['hangul','hanja','latin','number'],style:'font-serif'},
{id:12,name:'모노타입',scripts:['latin','number'],style:'font-mono'}
];
function normalizeLang(value=''){const v=String(value).toLowerCase();if(v.includes('hant')||v.startsWith('zh-tw')||v.startsWith('zh-hk'))return'zh-Hant';if(v.startsWith('zh'))return'zh-Hans';if(v.startsWith('ja'))return'ja';if(v.startsWith('en'))return'en';return'ko';}
function currentLang(){const query=new URLSearchParams(location.search).get('lang');return normalizeLang(query||localStorage.getItem('blueblack-language')||navigator.language);}
let lang=currentLang();let filter='all';
const grid=document.querySelector('#engravingFontGrid');const controls=document.querySelector('#engravingFilter');const input=document.querySelector('#engravingPreviewText');const summary=document.querySelector('#engravingResultSummary');
function t(){return COPY[lang]||COPY.ko;}
function money(value){return new Intl.NumberFormat(lang==='ko'?'ko-KR':'en-US').format(value)+(lang==='ko'?'원':' KRW');}
function installPricing(){if(document.querySelector('#engravingPricing'))return;const style=document.createElement('style');style.textContent='.engraving-main:before{display:none!important}.engraving-caution li:first-child{display:list-item!important}.engraving-caution ul:before{display:none!important}.engraving-price-grid{display:grid;grid-template-columns:repeat(3,minmax(0,1fr));gap:10px;margin-top:15px}.engraving-price-card{padding:16px;border:1px solid #d8e2eb;border-radius:16px;background:#fff}.engraving-price-card small{display:block;color:#a77a3d;font-size:8px;font-weight:900}.engraving-price-card strong{display:block;margin-top:7px;color:#10233f;font-size:19px}.engraving-price-card p{margin:6px 0 0;color:#66768a;font-size:9px;line-height:1.6}.engraving-price-total{display:flex;flex-wrap:wrap;gap:8px;margin-top:12px}.engraving-price-total span{padding:8px 10px;border-radius:999px;background:#10233f;color:#fff;font-size:9px;font-weight:900}.engraving-price-note{margin-top:12px;padding:12px 14px;border-left:3px solid #a77a3d;border-radius:10px;background:#fffaf2;color:#6d5a44;font-size:9px;line-height:1.65}@media(max-width:680px){.engraving-price-grid{grid-template-columns:1fr}}';document.head.append(style);const section=document.createElement('section');section.id='engravingPricing';section.className='detail-card engraving-service-summary';section.innerHTML='<div class="engraving-section-heading"><div><small>PRICE & METHOD</small><h2 data-price="title"></h2></div><p data-price="intro"></p></div><div class="engraving-price-grid"><article class="engraving-price-card"><small>LASER</small><strong>'+money(3500)+'</strong><p data-price="laserBody"></p></article><article class="engraving-price-card"><small>CARVED</small><strong>'+money(5000)+'</strong><p data-price="carvingBody"></p></article><article class="engraving-price-card"><small>SAME DAY</small><strong>+'+money(1000)+'</strong><p data-price="sameDayBody"></p></article></div><div class="engraving-price-total"><span data-price="laserToday"></span><span data-price="carvingToday"></span></div><div class="engraving-price-note" data-price="scope"></div>';document.querySelector('.engraving-source-card')?.before(section);}
function renderPricing(){const c=t();document.querySelector('[data-price="title"]')?.replaceChildren(c.serviceTitle);document.querySelector('[data-price="intro"]')?.replaceChildren(c.serviceIntro);document.querySelector('[data-price="laserBody"]')?.replaceChildren(c.laserBody);document.querySelector('[data-price="carvingBody"]')?.replaceChildren(c.carvingBody);document.querySelector('[data-price="sameDayBody"]')?.replaceChildren(c.sameDayBody);document.querySelector('[data-price="laserToday"]')?.replaceChildren(`${c.laserToday} ${money(4500)}`);document.querySelector('[data-price="carvingToday"]')?.replaceChildren(`${c.carvingToday} ${money(6000)}`);document.querySelector('[data-price="scope"]')?.replaceChildren(c.scope);}
function renderControls(){const labels=['all','hangul','hanja','latin','number'];if(!controls)return;controls.innerHTML='';labels.forEach(key=>{const button=document.createElement('button');button.type='button';button.textContent=t()[key];button.setAttribute('aria-pressed',String(filter===key));button.addEventListener('click',()=>{filter=key;renderControls();renderFonts();});controls.append(button);});}
function escapeHtml(value){return value.replace(/[&<>"']/g,ch=>({'&':'&amp;','<':'&lt;','>':'&gt;','"':'&quot;',"'":'&#39;'}[ch]));}
function renderFonts(){if(!grid||!summary||!input)return;const text=input.value.trim()||'BlueBlack 2026';const items=FONTS.filter(font=>filter==='all'||font.scripts.includes(filter));summary.textContent=t().result(items.length);grid.innerHTML='';if(!items.length){grid.innerHTML=`<div class="engraving-empty">${t().empty}</div>`;return;}items.forEach(font=>{const card=document.createElement('article');card.className=`engraving-font-card ${font.style}`;card.innerHTML=`<div class="engraving-font-head"><div><strong>${font.name}</strong></div><b>${String(font.id).padStart(2,'0')}</b></div>${font.note?`<em>${t().cursiveNote}</em>`:''}<div class="engraving-preview">${escapeHtml(text)}</div><div class="engraving-support">${font.scripts.map(key=>`<span>${t()[key]}</span>`).join('')}</div>`;grid.append(card);});}
function applyLanguage(){lang=currentLang();document.documentElement.lang=lang;document.querySelectorAll('[data-engraving-t]').forEach(node=>{const value=t()[node.dataset.engravingT];if(typeof value==='string')node.textContent=value;});document.title=t().pageTitle;renderPricing();renderControls();renderFonts();}
installPricing();input?.addEventListener('input',renderFonts);document.querySelectorAll('[data-portal-lang]').forEach(button=>button.addEventListener('click',()=>queueMicrotask(applyLanguage)));applyLanguage();
