const LANGUAGES=['ko','en','ja','zh-Hans','zh-Hant'];

const messages={
ko:{title:'세일러 펜뷔페 미리보기',intro:'여섯 개 파츠의 색상을 직접 조합하고 완성 모습을 3D로 확인해보세요. 최종 선택은 매장에서 실물 파츠와 함께 확인해 드립니다.',storePreview:'매장 상담용 미리보기',howTo:'이용 방법',howToCopy:'파츠와 색상을 고른 뒤 3D로 확인하고, 마음에 드는 조합은 링크나 이미지로 저장해 주세요.',step1:'파츠 선택',step1Copy:'캡부터 배럴앤드까지 6개 파츠를 차례로 선택합니다.',step2:'색상 선택',step2Copy:'각 파츠에 원하는 수지 컬러 또는 메탈 컬러를 적용합니다.',step3:'실물 확인',step3Copy:'매장에서 실제 색상과 투명도를 확인한 뒤 조립을 진행합니다.',preview:'3D 미리보기',assembled:'완성 모습',exploded:'파츠 분리',largeView:'크게 보기',close:'닫기',resetView:'시점 초기화',zoomIn:'확대',zoomOut:'축소',viewerHint:'한 손가락으로 회전 · 두 손가락으로 확대·축소',loading:'3D 미리보기를 준비하고 있습니다.',error:'3D 미리보기를 불러오지 못했습니다. 페이지를 새로고침해 주세요.',customize:'파츠별 색상을 골라주세요',partProgress:'{current} / {total}',selectedColor:'선택한 색상',originalColors:'기존 컬러',newColors:'신규 컬러',metalColors:'메탈 컬러',nextPart:'다음 파츠',previousPart:'이전 파츠',finishSelection:'선택 결과 확인',colorNotice:'화면 색상은 조명과 디스플레이 환경에 따라 실제 파츠와 다르게 보일 수 있습니다. 최종 선택 전 매장 실물을 확인해 주세요.',converterTitle:'컨버터 안내',converterCopy:'잉크 컨버터는 펜뷔페 기본 구성에 포함되지 않는 별도 구매 상품입니다.',resultTitle:'선택한 조합',resultCopy:'아래 목록을 매장 실물 파츠와 비교해 주세요.',share:'조합 공유하기',saveImage:'조합 이미지 저장',staffView:'직원과 함께 확인',reset:'새 조합 만들기',shared:'조합 링크를 공유했습니다.',copied:'조합 링크를 복사했습니다.',imageSaved:'조합 이미지를 저장했습니다.',resetDone:'기본 조합으로 초기화했습니다.',staffTitle:'선택 파츠 확인',staffCopy:'고객님이 선택한 색상입니다. 실물 파츠와 하나씩 비교해 주세요.',visitTitle:'블루블랙 펜샵 방문 안내',visitCopy:'특정 색상을 찾으신다면 방문 전 재고 문의를 권장드립니다.',address:'매장 주소',hours:'영업시간',phone:'전화 문의',weekday:'월–금 10:00–18:00',saturday:'토요일 12:00–18:00',closed:'일요일·공휴일 휴무',map:'네이버지도',call:'전화하기',website:'공식 홈페이지',instagram:'인스타그램',visitNote:'영업시간·휴무일·재고는 변경될 수 있습니다. 방문 전 공식 채널에서 최신 안내를 확인해 주세요.',footer:'본 페이지는 블루블랙 펜샵 매장 상담을 위한 조합 미리보기 도구입니다.'},
en:{title:'Sailor Pen Buffet Preview',intro:'Choose colors for six individual parts and review the finished pen in 3D. Please confirm the physical parts in store before making your final selection.',storePreview:'In-store consultation preview',howTo:'How to use',howToCopy:'Choose the parts and colors, review the pen in 3D, then save your preferred combination as a link or image.',step1:'Choose a part',step1Copy:'Select the six parts in order, from the cap to the barrel end.',step2:'Choose a color',step2Copy:'Apply a resin or metal color to each selected part.',step3:'Confirm in store',step3Copy:'Compare the physical color and translucency before assembly.',preview:'3D preview',assembled:'Finished pen',exploded:'Separate parts',largeView:'Large view',close:'Close',resetView:'Reset view',zoomIn:'Zoom in',zoomOut:'Zoom out',viewerHint:'Drag to rotate · Pinch with two fingers to zoom',loading:'Preparing the 3D preview.',error:'The 3D preview could not be loaded. Please refresh the page.',customize:'Choose a color for each part',partProgress:'{current} / {total}',selectedColor:'Selected color',originalColors:'Original colors',newColors:'New colors',metalColors:'Metal colors',nextPart:'Next part',previousPart:'Previous part',finishSelection:'Review selection',colorNotice:'Colors may appear different depending on lighting and your display. Please confirm the physical parts in store before making your final choice.',converterTitle:'Converter information',converterCopy:'The ink converter is sold separately and is not included in the Pen Buffet base set.',resultTitle:'Your selected combination',resultCopy:'Compare this list with the physical parts in store.',share:'Share combination',saveImage:'Save combination image',staffView:'Review with staff',reset:'Create a new combination',shared:'Combination shared.',copied:'Combination link copied.',imageSaved:'Combination image saved.',resetDone:'Reset to the default combination.',staffTitle:'Selected parts',staffCopy:'These are the selected colors. Please compare each item with the physical parts.',visitTitle:'Visit BlueBlack Pen Shop',visitCopy:'We recommend checking stock before visiting if you are looking for a specific color.',address:'Store address',hours:'Opening hours',phone:'Phone',weekday:'Mon–Fri 10:00–18:00',saturday:'Saturday 12:00–18:00',closed:'Closed Sundays and public holidays',map:'Naver Map',call:'Call',website:'Official website',instagram:'Instagram',visitNote:'Opening hours, closing days and stock may change. Please check the official channels before visiting.',footer:'This page is a combination preview tool for in-store consultation at BlueBlack Pen Shop.'},
ja:{title:'セーラー万年筆ビュッフェ プレビュー',intro:'6つのパーツにお好みの色を組み合わせ、完成イメージを3Dでご確認いただけます。最終選択前に店頭で実物パーツをご確認ください。',storePreview:'店頭接客用プレビュー',howTo:'ご利用方法',howToCopy:'パーツと色を選び、3Dで確認した後、お好みの組み合わせをリンクまたは画像で保存してください。',step1:'パーツを選ぶ',step1Copy:'キャップから胴軸エンドまで6つのパーツを順番に選びます。',step2:'色を選ぶ',step2Copy:'各パーツに樹脂カラーまたは金属カラーを適用します。',step3:'店頭で確認',step3Copy:'実物の色と透明感を確認してから組み立てを行います。',preview:'3Dプレビュー',assembled:'完成イメージ',exploded:'パーツ分解',largeView:'大きく見る',close:'閉じる',resetView:'視点をリセット',zoomIn:'拡大',zoomOut:'縮小',viewerHint:'指で回転 · 2本指で拡大・縮小',loading:'3Dプレビューを準備しています。',error:'3Dプレビューを読み込めませんでした。ページを再読み込みしてください。',customize:'パーツごとに色をお選びください',partProgress:'{current} / {total}',selectedColor:'選択中の色',originalColors:'既存カラー',newColors:'新色',metalColors:'金属カラー',nextPart:'次のパーツ',previousPart:'前のパーツ',finishSelection:'選択結果を確認',colorNotice:'照明やディスプレイ環境により、画面の色は実物と異なる場合があります。最終選択前に店頭で実物をご確認ください。',converterTitle:'コンバーターについて',converterCopy:'インクコンバーターは基本セットに含まれない別売り商品です。',resultTitle:'選択した組み合わせ',resultCopy:'店頭の実物パーツと下記の内容を比較してください。',share:'組み合わせを共有',saveImage:'組み合わせ画像を保存',staffView:'スタッフと確認',reset:'新しい組み合わせを作る',shared:'組み合わせを共有しました。',copied:'組み合わせリンクをコピーしました。',imageSaved:'組み合わせ画像を保存しました。',resetDone:'初期の組み合わせに戻しました。',staffTitle:'選択パーツの確認',staffCopy:'お客様が選択した色です。実物パーツと一つずつ比較してください。',visitTitle:'BlueBlack Pen Shop 店舗案内',visitCopy:'特定の色をご希望の場合は、ご来店前の在庫確認をおすすめします。',address:'店舗住所',hours:'営業時間',phone:'電話',weekday:'月〜金 10:00–18:00',saturday:'土曜日 12:00–18:00',closed:'日曜・祝日休業',map:'NAVERマップ',call:'電話する',website:'公式サイト',instagram:'Instagram',visitNote:'営業時間・休業日・在庫は変更される場合があります。ご来店前に公式情報をご確認ください。',footer:'本ページはBlueBlack Pen Shopの店頭接客用組み合わせプレビューツールです。'},
'zh-Hans':{title:'钢笔自助配色预览',intro:'自由搭配六个部件的颜色，并通过3D查看完成效果。最终选择前，请在店内确认实物部件。',storePreview:'店内咨询预览',howTo:'使用方法',howToCopy:'选择部件和颜色，通过3D确认后，可将喜欢的组合保存为链接或图片。',step1:'选择部件',step1Copy:'依次选择笔帽至笔杆尾部的六个部件。',step2:'选择颜色',step2Copy:'为每个部件选择树脂色或金属色。',step3:'确认实物',step3Copy:'组装前请在店内确认实际颜色与透明感。',preview:'3D预览',assembled:'完成效果',exploded:'分离部件',largeView:'放大查看',close:'关闭',resetView:'重置视角',zoomIn:'放大',zoomOut:'缩小',viewerHint:'单指旋转 · 双指缩放',loading:'正在准备3D预览。',error:'无法加载3D预览，请刷新页面。',customize:'请选择各部件的颜色',partProgress:'{current} / {total}',selectedColor:'已选颜色',originalColors:'原有颜色',newColors:'新颜色',metalColors:'金属颜色',nextPart:'下一个部件',previousPart:'上一个部件',finishSelection:'查看选择结果',colorNotice:'受照明和显示设备影响，屏幕颜色可能与实物不同。最终选择前请在店内确认实物。',converterTitle:'上墨器说明',converterCopy:'上墨器不包含在基础套装内，需要另行购买。',resultTitle:'已选组合',resultCopy:'请与店内实物部件逐一对照。',share:'分享组合',saveImage:'保存组合图片',staffView:'与店员一起确认',reset:'创建新组合',shared:'组合已分享。',copied:'组合链接已复制。',imageSaved:'组合图片已保存。',resetDone:'已恢复默认组合。',staffTitle:'确认所选部件',staffCopy:'以下是您选择的颜色，请与实物部件逐一确认。',visitTitle:'BlueBlack Pen Shop 到店信息',visitCopy:'如需特定颜色，建议到店前咨询库存。',address:'门店地址',hours:'营业时间',phone:'电话咨询',weekday:'周一至周五 10:00–18:00',saturday:'周六 12:00–18:00',closed:'周日及节假日休息',map:'Naver地图',call:'拨打电话',website:'官方网站',instagram:'Instagram',visitNote:'营业时间、休息日和库存可能变更，到店前请查看官方渠道的最新信息。',footer:'本页面是BlueBlack Pen Shop店内咨询用的配色预览工具。'},
'zh-Hant':{title:'鋼筆自助配色預覽',intro:'自由搭配六個部件的顏色，並透過3D查看完成效果。最終選擇前，請在店內確認實物部件。',storePreview:'店內諮詢預覽',howTo:'使用方法',howToCopy:'選擇部件和顏色，透過3D確認後，可將喜歡的組合儲存為連結或圖片。',step1:'選擇部件',step1Copy:'依序選擇筆帽至筆桿尾部的六個部件。',step2:'選擇顏色',step2Copy:'為每個部件選擇樹脂色或金屬色。',step3:'確認實物',step3Copy:'組裝前請在店內確認實際顏色與透明感。',preview:'3D預覽',assembled:'完成效果',exploded:'分離部件',largeView:'放大查看',close:'關閉',resetView:'重設視角',zoomIn:'放大',zoomOut:'縮小',viewerHint:'單指旋轉 · 雙指縮放',loading:'正在準備3D預覽。',error:'無法載入3D預覽，請重新整理頁面。',customize:'請選擇各部件的顏色',partProgress:'{current} / {total}',selectedColor:'已選顏色',originalColors:'原有顏色',newColors:'新顏色',metalColors:'金屬顏色',nextPart:'下一個部件',previousPart:'上一個部件',finishSelection:'查看選擇結果',colorNotice:'受照明和顯示設備影響，螢幕顏色可能與實物不同。最終選擇前請在店內確認實物。',converterTitle:'吸墨器說明',converterCopy:'吸墨器不包含在基本套裝內，需要另行購買。',resultTitle:'已選組合',resultCopy:'請與店內實物部件逐一對照。',share:'分享組合',saveImage:'儲存組合圖片',staffView:'與店員一起確認',reset:'建立新組合',shared:'組合已分享。',copied:'組合連結已複製。',imageSaved:'組合圖片已儲存。',resetDone:'已恢復預設組合。',staffTitle:'確認所選部件',staffCopy:'以下是您選擇的顏色，請與實物部件逐一確認。',visitTitle:'BlueBlack Pen Shop 到店資訊',visitCopy:'如需特定顏色，建議到店前詢問庫存。',address:'門市地址',hours:'營業時間',phone:'電話諮詢',weekday:'週一至週五 10:00–18:00',saturday:'週六 12:00–18:00',closed:'週日及國定假日休息',map:'Naver地圖',call:'撥打電話',website:'官方網站',instagram:'Instagram',visitNote:'營業時間、休息日和庫存可能變更，到店前請查看官方管道的最新資訊。',footer:'本頁面是BlueBlack Pen Shop店內諮詢用的配色預覽工具。'}
};

const partsZh={
'zh-Hans':{cap_body:['笔帽','关闭钢笔时保护笔尖的上部部件，也是决定整体第一印象的主要颜色区域。'],cap_end:['笔帽尾端','笔帽末端的小型点缀部件，可与笔帽同色或使用对比色。'],nib_grip:['握位','书写时手指接触、位于笔尖后方的握持部件。'],metal_parts:['金属部件','可为笔尖、笔夹、笔帽环和连接环选择银色或金色。'],barrel_body:['笔杆','握在手中的主要笔身，也是完成后面积最大的颜色区域。'],barrel_end:['笔杆尾端','笔杆末端的小型点缀部件，可与笔帽尾端呼应或形成对比。']},
'zh-Hant':{cap_body:['筆帽','關閉鋼筆時保護筆尖的上部部件，也是決定整體第一印象的主要顏色區域。'],cap_end:['筆帽尾端','筆帽末端的小型點綴部件，可與筆帽同色或使用對比色。'],nib_grip:['握位','書寫時手指接觸、位於筆尖後方的握持部件。'],metal_parts:['金屬部件','可為筆尖、筆夾、筆帽環和連接環選擇銀色或金色。'],barrel_body:['筆桿','握在手中的主要筆身，也是完成後面積最大的顏色區域。'],barrel_end:['筆桿尾端','筆桿末端的小型點綴部件，可與筆帽尾端呼應或形成對比。']}
};

const colorsZh={
'zh-Hans':{clear:'棕褐',white:'夜幕',black:'孔雀蓝',navy:'蜜瓜绿',blue:'胡萝卜',sky:'向日葵',green:'火烈鸟',yellow:'紫藤',pink:'薰衣草糖',red:'牛奶','skeleton-flower':'水晶花',rabbit:'兔子',sakuramochi:'樱花饼',strawberry:'草莓',apricot:'杏子','ginkgo-nuts':'银杏',jade:'翡翠',sapphire:'蓝宝石',akebia:'木通果',wolf:'狼灰',silver:'银色',gold:'金色'},
'zh-Hant':{clear:'棕褐',white:'夜幕',black:'孔雀藍',navy:'蜜瓜綠',blue:'胡蘿蔔',sky:'向日葵',green:'紅鶴',yellow:'紫藤',pink:'薰衣草糖',red:'牛奶','skeleton-flower':'水晶花',rabbit:'兔子',sakuramochi:'櫻花餅',strawberry:'草莓',apricot:'杏桃','ginkgo-nuts':'銀杏',jade:'翡翠',sapphire:'藍寶石',akebia:'木通果',wolf:'狼灰',silver:'銀色',gold:'金色'}
};

let currentLanguage='ko';
function normalize(value=''){const v=String(value).toLowerCase();if(v.startsWith('zh-tw')||v.startsWith('zh-hk')||v.startsWith('zh-mo')||v.includes('hant'))return'zh-Hant';if(v.startsWith('zh'))return'zh-Hans';if(v.startsWith('ja'))return'ja';if(v.startsWith('en'))return'en';if(v.startsWith('ko'))return'ko';return'';}
export function initializeLanguage(){const q=normalize(new URLSearchParams(location.search).get('lang'));const s=normalize(localStorage.getItem('blueblack-language'));const b=(navigator.languages??[navigator.language]).map(normalize).find(Boolean);currentLanguage=LANGUAGES.includes(q)?q:LANGUAGES.includes(s)?s:b||'ko';document.documentElement.lang=currentLanguage;return currentLanguage;}
export function getLanguage(){return currentLanguage;}
export function setLanguage(language){const next=normalize(language);if(!LANGUAGES.includes(next))return;currentLanguage=next;document.documentElement.lang=next;localStorage.setItem('blueblack-language',next);const query=new URLSearchParams(location.search);query.set('lang',next);history.replaceState(null,'',`${location.pathname}?${query}`);}
export function t(key,variables={}){let value=messages[currentLanguage]?.[key]??messages.ko[key]??key;for(const[name,replacement]of Object.entries(variables))value=value.replace(`{${name}}`,replacement);return value;}
export function localizePart(part){if(partsZh[currentLanguage]?.[part.id]){const[name,description]=partsZh[currentLanguage][part.id];return{name,description};}const suffix=currentLanguage==='ja'?'Ja':currentLanguage==='en'?'En':'Ko';return{name:part[`name${suffix}`]??part.nameKo,description:part[`description${suffix}`]??part.descriptionKo};}
export function localizeColor(color){if(colorsZh[currentLanguage]?.[color.id])return colorsZh[currentLanguage][color.id];if(currentLanguage==='ja')return color.nameJa??color.nameEn;if(currentLanguage==='en')return color.nameEn;return color.nameKo;}
