import * as THREE from 'three';
import { OrbitControls } from 'three/addons/controls/OrbitControls.js';
import { parts, colors, defaultSelection } from './data.js';
import { buildPenModel } from './pen-model.js';

const state={activePartId:parts[0].id,selections:{...defaultSelection},viewMode:'open',autoRotate:true,root:null,groups:null,partMeshes:new Map()};
const params=new URLSearchParams(location.search);const legacy={cap_end:'cap_top',nib_grip:'grip_section'};
for(const part of parts){const value=params.get(part.id)??params.get(legacy[part.id]);if(colors.some(c=>c.id===value&&c.group===part.colorGroup))state.selections[part.id]=value;}
const $=s=>document.querySelector(s),canvas=$('#pen-canvas'),wrap=$('#canvas-wrap'),loading=$('#loading-panel'),errorPanel=$('#model-error'),tabs=$('#part-tabs'),swatches=$('#swatch-grid'),summary=$('#summary-list'),feedback=$('#copy-feedback');
$('#loading-progress').textContent='모델 구성 중';
const renderer=new THREE.WebGLRenderer({canvas,antialias:true,alpha:true,preserveDrawingBuffer:true});renderer.setPixelRatio(Math.min(devicePixelRatio,2));renderer.outputColorSpace=THREE.SRGBColorSpace;renderer.toneMapping=THREE.ACESFilmicToneMapping;renderer.toneMappingExposure=1.05;renderer.shadowMap.enabled=true;renderer.shadowMap.type=THREE.PCFSoftShadowMap;
const scene=new THREE.Scene(),camera=new THREE.PerspectiveCamera(31,1,.1,1000);camera.position.set(0,46,188);
const controls=new OrbitControls(camera,canvas);controls.enableDamping=true;controls.dampingFactor=.065;controls.minDistance=100;controls.maxDistance=290;controls.autoRotate=true;controls.autoRotateSpeed=.5;
scene.add(new THREE.HemisphereLight(0xffffff,0x8e9aaa,2.15));for(const [color,intensity,pos] of [[0xffffff,3.4,[45,70,85]],[0xc6dbff,1.6,[-55,18,50]],[0xffebca,1.35,[20,-25,-50]]]){const light=new THREE.DirectionalLight(color,intensity);light.position.set(...pos);scene.add(light);}
const ground=new THREE.Mesh(new THREE.CircleGeometry(124,96),new THREE.ShadowMaterial({color:0x263548,opacity:.13}));ground.rotation.x=-Math.PI/2;ground.position.y=-24;ground.receiveShadow=true;scene.add(ground);
const materials={fixedMetal:new THREE.MeshStandardMaterial({color:0xc8ccd1,metalness:.92,roughness:.18}),darkMetal:new THREE.MeshStandardMaterial({color:0x555b63,metalness:.65,roughness:.25}),feedMaterial:new THREE.MeshStandardMaterial({color:0x16181c,roughness:.34}),darkInset:new THREE.MeshStandardMaterial({color:0x111318,roughness:.42}),customMaterial:()=>new THREE.MeshPhysicalMaterial({color:0xdce8ee,roughness:.16,clearcoat:.65,clearcoatRoughness:.14,transparent:true,opacity:.46,transmission:.12,thickness:1.1,side:THREE.DoubleSide})};
const getColor=id=>colors.find(c=>c.id===id)??colors[0],allMeshes=()=>[...state.partMeshes.values()].flat();
function resetGroups(){if(!state.groups)return;for(const g of Object.values(state.groups)){g.position.set(0,0,0);g.rotation.set(0,0,0);}}
function layout(){if(!state.groups)return;const{capEndGroup,capBodyGroup,nibGripGroup,barrelGroup,barrelEndGroup}=state.groups;resetGroups();if(state.viewMode==='open'){capEndGroup.position.set(-8,30,0);capBodyGroup.position.set(8,30,0);nibGripGroup.position.set(-8,-7,0);barrelGroup.position.set(8,-7,0);barrelEndGroup.position.set(21,-7,0);state.root.position.set(-6,-3,0);camera.position.set(0,52,202);ground.position.y=-28;}else{capEndGroup.position.set(22.2,0,0);capBodyGroup.position.set(22.2,0,0);state.root.position.set(-8,0,0);camera.position.set(0,28,180);ground.position.y=-13;}controls.target.set(0,0,0);controls.update();}
function paint(mesh,color,active,isMetal){const m=mesh.material;m.color.set(color.hex);m.metalness=isMetal?(color.metalness??.9):0;m.roughness=isMetal?(color.roughness??.2):(color.transparent?.08:.17);m.clearcoat=isMetal?.25:.74;m.clearcoatRoughness=isMetal?.2:.11;m.transparent=isMetal?false:!!color.transparent;m.opacity=isMetal?1:(color.transparent?.43:1);m.transmission=isMetal?0:(color.transparent?.13:0);m.depthWrite=isMetal||!color.transparent;m.side=!isMetal&&color.transparent?THREE.DoubleSide:THREE.FrontSide;m.emissive=new THREE.Color(active?color.hex:'#000000');m.emissiveIntensity=active?.035:0;m.needsUpdate=true;}
function applyColors(){for(const part of parts){const color=getColor(state.selections[part.id]);for(const mesh of state.partMeshes.get(part.id)??[])paint(mesh,color,state.activePartId===part.id,part.colorGroup==='metal');}}
function saveQuery(){const q=new URLSearchParams();for(const p of parts)q.set(p.id,state.selections[p.id]);history.replaceState(null,'',`${location.pathname}?${q}`);}
const code=()=>`BB-SAILOR-${parts.map(p=>getColor(state.selections[p.id]).code).join('-')}`;
function selectPart(id){state.activePartId=id;applyColors();render();}
function renderTabs(){tabs.replaceChildren(...parts.map((p,i)=>{const b=document.createElement('button');b.type='button';b.className='part-tab';b.role='tab';b.textContent=`${i+1}. ${p.nameKo}`;b.setAttribute('aria-selected',String(state.activePartId===p.id));b.onclick=()=>selectPart(p.id);return b;}));}
function renderSwatches(){const part=parts.find(p=>p.id===state.activePartId),active=state.selections[part.id],list=colors.filter(c=>c.group===part.colorGroup);swatches.replaceChildren(...list.map(c=>{const b=document.createElement('button');b.type='button';b.className='swatch-button';b.role='radio';b.setAttribute('aria-checked',String(active===c.id));b.innerHTML=`<span class="swatch-circle${c.transparent?' transparent':''}" style="background:${c.hex}"></span><span>${c.nameKo}</span>`;b.onclick=()=>{state.selections[part.id]=c.id;saveQuery();applyColors();render();};return b;}));}
function renderSummary(){summary.replaceChildren(...parts.map(p=>{const c=getColor(state.selections[p.id]),d=document.createElement('div');d.className='summary-item';d.innerHTML=`<span class="summary-dot" style="background:${c.hex}"></span><div><small>${p.nameKo}</small><b>${c.nameKo}</b></div>`;return d;}));$('#combination-code').textContent=code();}
function render(){const i=parts.findIndex(p=>p.id===state.activePartId),p=parts[i],c=getColor(state.selections[p.id]);$('#progress-text').textContent=`${i+1} / ${parts.length}`;$('#part-name-en').textContent=p.nameEn;$('#part-name-ko').textContent=p.nameKo;$('#part-description').textContent=p.description;$('#selected-color-name').textContent=`${c.nameKo} · ${c.nameEn}`;$('#selected-color-dot').style.background=c.hex;renderTabs();renderSwatches();renderSummary();}
function resize(){const w=wrap.clientWidth,h=wrap.clientHeight;renderer.setSize(w,h,false);camera.aspect=w/h;camera.updateProjectionMatrix();}
function toast(msg){feedback.textContent=msg;setTimeout(()=>{if(feedback.textContent===msg)feedback.textContent='';},2600);}
try{const model=buildPenModel(materials);state.root=model.root;state.groups=model.groups;state.partMeshes=model.partMeshes;scene.add(state.root);layout();applyColors();loading.hidden=true;}catch(e){console.error(e);loading.hidden=true;errorPanel.hidden=false;}
new ResizeObserver(resize).observe(wrap);const raycaster=new THREE.Raycaster(),pointer=new THREE.Vector2();canvas.addEventListener('pointerup',e=>{if(!state.root||e.pointerType==='touch')return;const r=canvas.getBoundingClientRect();pointer.x=(e.clientX-r.left)/r.width*2-1;pointer.y=-(e.clientY-r.top)/r.height*2+1;raycaster.setFromCamera(pointer,camera);const id=raycaster.intersectObjects(allMeshes(),false)[0]?.object?.userData?.partId;if(id)selectPart(id);});
$('#toggle-rotate').onclick=e=>{state.autoRotate=!state.autoRotate;e.currentTarget.textContent=`자동 회전 ${state.autoRotate?'켬':'끔'}`;};
$('#toggle-view').onclick=e=>{state.viewMode=state.viewMode==='open'?'closed':'open';e.currentTarget.textContent=state.viewMode==='open'?'완성 상태 보기':'파츠 분리 보기';$('#view-title').textContent=state.viewMode==='open'?'파츠 분리 보기':'완성 상태 보기';layout();};
$('#copy-link').onclick=async()=>{try{await navigator.clipboard.writeText(location.href);toast('조합 링크를 복사했습니다.');}catch{toast('주소창의 링크를 직접 복사해 주세요.');}};
$('#save-image').onclick=()=>{renderer.render(scene,camera);canvas.toBlob(blob=>{if(!blob)return;const a=document.createElement('a');a.href=URL.createObjectURL(blob);a.download=`${code()}.png`;a.click();URL.revokeObjectURL(a.href);toast('현재 3D 화면을 이미지로 저장했습니다.');},'image/png');};
$('#reset-combination').onclick=()=>{state.selections={...defaultSelection};state.activePartId=parts[0].id;saveQuery();applyColors();render();toast('기본 조합으로 초기화했습니다.');};
render();resize();(function animate(){controls.autoRotate=state.autoRotate;controls.update();renderer.render(scene,camera);requestAnimationFrame(animate);})();
