const copy={
ko:['매장 기기에 설치','설치 준비 중…','인터넷 연결이 끊겨 저장된 화면으로 전환했습니다.','인터넷 연결이 복구되었습니다.','새 버전을 사용할 수 있습니다.','업데이트'],
en:['Install on store device','Preparing installation…','Connection lost. Using the saved offline version.','Internet connection restored.','A new version is available.','Update'],
ja:['店舗端末にインストール','インストール準備中…','接続が切れたため、保存済みのオフライン版を使用します。','インターネット接続が復旧しました。','新しいバージョンがあります。','更新'],
'zh-Hans':['安装到门店设备','正在准备安装…','网络已断开，正在使用已保存的离线版本。','网络连接已恢复。','有新版本可用。','更新'],
'zh-Hant':['安裝到門市裝置','正在準備安裝…','網路已斷開，正在使用已儲存的離線版本。','網路連線已恢復。','有新版本可用。','更新']};
const ROOT=new URL('../',import.meta.url);
function lang(){const value=document.documentElement.lang||'ko';if(value.startsWith('zh-Hant'))return'zh-Hant';if(value.startsWith('zh'))return'zh-Hans';if(value.startsWith('ja'))return'ja';if(value.startsWith('en'))return'en';return'ko';}
const text=()=>copy[lang()]||copy.ko;
const store=()=>{const q=new URLSearchParams(location.search);return q.get('mode')==='store'||q.get('staff')==='1'||matchMedia('(display-mode:standalone)').matches;};
function style(){if(document.querySelector('link[data-pwa-v9]'))return;const link=document.createElement('link');link.rel='stylesheet';link.href=new URL('pwa-v6.css',ROOT).href;link.dataset.pwaV9='1';document.head.append(link);}
function toast(message){let node=document.querySelector('.network-toast');if(!node){node=document.createElement('div');node.className='network-toast';node.setAttribute('role','status');document.body.append(node);}node.textContent=message;node.classList.add('is-visible');clearTimeout(toast.timer);toast.timer=setTimeout(()=>node.classList.remove('is-visible'),3000);}
function install(){if(!store())return;const anchor=document.querySelector('.language-switcher');if(!anchor)return;const button=document.createElement('button');button.type='button';button.className='install-app-button';button.textContent=text()[0];anchor.insertAdjacentElement('afterend',button);let eventRef;addEventListener('beforeinstallprompt',event=>{event.preventDefault();eventRef=event;button.classList.add('is-visible');});button.addEventListener('click',async()=>{if(!eventRef)return;button.textContent=text()[1];await eventRef.prompt();await eventRef.userChoice;eventRef=null;button.classList.remove('is-visible');});}
function update(registration){if(!store()||document.querySelector('.update-banner'))return;const banner=document.createElement('div');banner.className='update-banner';banner.innerHTML='<span></span><button type="button"></button>';banner.querySelector('span').textContent=text()[4];banner.querySelector('button').textContent=text()[5];banner.querySelector('button').addEventListener('click',()=>registration.waiting?.postMessage({type:'SKIP_WAITING'}));document.body.append(banner);}
async function register(){if(!('serviceWorker'in navigator))return;try{const registration=await navigator.serviceWorker.register(new URL('sw.js',ROOT),{scope:ROOT.pathname});if(registration.waiting&&navigator.serviceWorker.controller)update(registration);registration.addEventListener('updatefound',()=>registration.installing?.addEventListener('statechange',()=>{if(registration.installing?.state==='installed'&&navigator.serviceWorker.controller)update(registration);}));navigator.serviceWorker.addEventListener('controllerchange',()=>location.reload());}catch(error){console.warn(error);}}
style();addEventListener('offline',()=>toast(text()[2]));addEventListener('online',()=>toast(text()[3]));setTimeout(install);register();