const STORAGE_KEY='blueblack-pen-combination-query';
const TOUCHED_KEY='blueblack-pen-completed-parts';
const PART_IDS=['cap_body','cap_end','nib_grip','metal_parts','barrel_body','barrel_end'];
const copy={
ko:{title:'새 조합을 시작할까요?',body:'이 기기에 이전에 만들던 조합이 저장되어 있습니다.',fresh:'새 조합 시작',freshBody:'기본 색상으로 초기화하고 처음부터 선택합니다.',resume:'이전 조합 이어서',resumeBody:'마지막으로 선택한 색상 조합을 다시 불러옵니다.',idleTitle:'다음 고객을 위해 화면을 정리할까요?',idleBody:'일정 시간 동안 조작이 없어 현재 조합을 초기화할 수 있습니다.',reset:'새 고객 시작',resetBody:'현재 조합을 지우고 기본 화면으로 돌아갑니다.',keep:'현재 조합 유지',keepBody:'지금 화면을 그대로 계속 사용합니다.'},
en:{title:'Start a new combination?',body:'A previous combination is saved on this device.',fresh:'Start a new combination',freshBody:'Reset to the default colors and begin again.',resume:'Continue previous combination',resumeBody:'Restore the last selected colors.',idleTitle:'Prepare the screen for the next customer?',idleBody:'There has been no activity for a while. You can reset the current combination.',reset:'Start for a new customer',resetBody:'Clear the current combination and return to the default view.',keep:'Keep current combination',keepBody:'Continue using the current screen.'},
ja:{title:'新しい組み合わせを始めますか？',body:'この端末には前回作成した組み合わせが保存されています。',fresh:'新しい組み合わせを始める',freshBody:'基本カラーに戻して最初から選択します。',resume:'前回の組み合わせを続ける',resumeBody:'最後に選択した色の組み合わせを復元します。',idleTitle:'次のお客様のために画面を初期化しますか？',idleBody:'しばらく操作がありませんでした。現在の組み合わせを初期化できます。',reset:'新しいお客様を開始',resetBody:'現在の組み合わせを消して基本画面に戻ります。',keep:'現在の組み合わせを維持',keepBody:'現在の画面をそのまま使用します。'},
'zh-Hans':{title:'开始新的配色吗？',body:'此设备中保存了上次编辑的配色。',fresh:'开始新配色',freshBody:'恢复默认颜色并从头开始选择。',resume:'继续上次配色',resumeBody:'恢复上次选择的颜色组合。',idleTitle:'为下一位顾客重置画面吗？',idleBody:'一段时间没有操作，可以重置当前配色。',reset:'开始新顾客',resetBody:'清除当前配色并返回默认画面。',keep:'保留当前配色',keepBody:'继续使用当前画面。'},
'zh-Hant':{title:'開始新的配色嗎？',body:'此裝置中儲存了上次編輯的配色。',fresh:'開始新配色',freshBody:'恢復預設顏色並從頭開始選擇。',resume:'繼續上次配色',resumeBody:'恢復上次選擇的顏色組合。',idleTitle:'為下一位顧客重設畫面嗎？',idleBody:'一段時間沒有操作，可以重設目前配色。',reset:'開始新顧客',resetBody:'清除目前配色並返回預設畫面。',keep:'保留目前配色',keepBody:'繼續使用目前畫面。'}
};
function lang(){const v=document.documentElement.lang||'ko';if(v.startsWith('zh-Hant'))return'zh-Hant';if(v.startsWith('zh'))return'zh-Hans';if(v.startsWith('ja'))return'ja';if(v.startsWith('en'))return'en';return'ko';}
function t(){return copy[lang()]||copy.ko;}
function hasSelection(){const q=new URLSearchParams(location.search);return PART_IDS.some(id=>q.has(id));}
function saved(){return localStorage.getItem(STORAGE_KEY);}
function clear(){localStorage.removeItem(STORAGE_KEY);localStorage.removeItem(TOUCHED_KEY);window.blueblackPenApp?.resetCombination?.();}
function resume(){const value=saved();if(value)location.assign(`${location.pathname}?${new URLSearchParams(value)}`);}
function dialog(){let d=document.querySelector('#session-dialog');if(d)return d;d=document.createElement('dialog');d.id='session-dialog';d.className='session-dialog';d.innerHTML='<div class="session-dialog-body"><div class="session-dialog-head"><div><h2></h2><p></p></div></div><div class="session-choice"><button type="button" class="session-primary"><b></b><span></span></button><button type="button" class="session-secondary"><b></b><span></span></button></div></div>';document.body.append(d);return d;}
function open(mode='resume'){const d=dialog(),v=t();const old1=d.querySelector('.session-primary'),old2=d.querySelector('.session-secondary');old1.replaceWith(old1.cloneNode(true));old2.replaceWith(old2.cloneNode(true));const a=d.querySelector('.session-primary'),b=d.querySelector('.session-secondary');if(mode==='idle'){d.querySelector('h2').textContent=v.idleTitle;d.querySelector('p').textContent=v.idleBody;a.querySelector('b').textContent=v.reset;a.querySelector('span').textContent=v.resetBody;b.querySelector('b').textContent=v.keep;b.querySelector('span').textContent=v.keepBody;a.addEventListener('click',()=>{clear();d.close();});b.addEventListener('click',()=>d.close());}else{d.querySelector('h2').textContent=v.title;d.querySelector('p').textContent=v.body;a.querySelector('b').textContent=v.fresh;a.querySelector('span').textContent=v.freshBody;b.querySelector('b').textContent=v.resume;b.querySelector('span').textContent=v.resumeBody;a.addEventListener('click',()=>{clear();d.close();});b.addEventListener('click',resume);}d.showModal();}
function setupResume(){if(!hasSelection()&&saved())open();}
function setupIdle(){const store=matchMedia('(min-width:700px)').matches||new URLSearchParams(location.search).get('mode')==='store';if(!store)return;let timer;const reset=()=>{clearTimeout(timer);timer=setTimeout(()=>{if(!document.hidden&&!document.querySelector('dialog[open]'))open('idle');},12*60*1000);};['pointerdown','keydown','touchstart','wheel'].forEach(event=>addEventListener(event,reset,{passive:true}));reset();}
setTimeout(()=>{setupResume();setupIdle();},0);
